# DNSC 6305 Final Project Group Number 2:
* Prithak Bhattacharyya
* Ayushi Chauhan
* Jenny Choi
* Sadman Noor
* Katherine Scheuer
* Ellie Zhen
* Wenyuan Zou

# Attestation
Each member of the group affirms that we have followed George Washington University’s Code of Academic Integrity and has followed the instructions mentioned while completing this Final project. We attest that all the work done is our own  and we have not used any resources which are not permissible.
We understand and adhere to the zero-tolerance academic policy towards plagiarism which may lead to strict penalties.

In [1]:
from IPython.display import Image
Image(url="https://github.com/pkbhatta5/GWU-DNSC-6305/blob/75d120397b27b5ccebba26848a17b4b6ab697d11/Attestation%20Screenshot.png?raw=true")

## Ask 1 (10%) - Fetching the Data
Use the JHU datasets website, collect the following datasets:
- Cases and Deaths (04/12/2020 – 11/15/2021)
- Vaccine 
- People Vaccinated (12/10/2020 – 11/15/2021)
- Testing

The readme/dictionary files are available for all datasets
Cases and Deaths, Vaccine and Testing
Acquire daily U.S. report. Perform initial exploration to make sure it is suitable
for dimensional modeling and analytical analysis

- Expectation: Provide a list of your data sources, The links to the data sources
and links to any documentations you used. 

#### Below are the data sources from where we pull the data for vaccine, people vaccinated, testing, cases and deaths. Also, mentioned is the readme file


### Vaccine data 
https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/vaccine_data/us_data/time_series/vaccine_data_us_timeline.csv

### People vaccinated
https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/vaccine_data/us_data/time_series/people_vaccinated_us_timeline.csv

### Testing
https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/testing_data/time_series_covid19_US.csv

### Cases and Deaths
https://github.com/pkbhatta5/GWU-DNSC-6305/blob/a1e3b2b48d9180bd7e37fd97345033ba728377bb/cases.csv

### Readme

##### JHU COVID-19 Dataset
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/README.md

##### Cases and Deaths
https://github.com/CSSEGISandData/COVID-19/blob/e34f38657d2f9c41ce66ee383923cec41e1c581c/csse_covid_19_data/README.md

##### Vaccine
https://github.com/govex/COVID-19/blob/1d6ba41028ae5c3e2a982f322ab21381365e2138/data_tables/vaccine_data/us_data/data_dictionary.csv

##### Testing
https://github.com/govex/COVID-19/blob/1d6ba41028ae5c3e2a982f322ab21381365e2138/data_tables/testing_data/data_dictionary.csv

### Getting the tables for exploratory analysis

In [2]:
# Using python to read csv and explore data
# Import the padas library

In [3]:
import pandas as pd

In [4]:
# Read file and store the data in variable- "Vaccine"
vaccine = pd.read_csv("https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/vaccine_data/us_data/time_series/vaccine_data_us_timeline.csv")

# Display the result
vaccine

Province_State        Date Vaccine_Type  FIPS Country_Region      Lat  \
0             Alabama  2020-12-10          All   1.0             US  32.3182   
1             Alabama  2020-12-10      Moderna   1.0             US  32.3182   
2             Alabama  2020-12-10       Pfizer   1.0             US  32.3182   
3             Alabama  2020-12-11          All   1.0             US  32.3182   
4             Alabama  2020-12-11      Moderna   1.0             US  32.3182   
...               ...         ...          ...   ...            ...      ...   
121367        Wyoming  2021-12-10      Moderna  56.0             US  42.7560   
121368        Wyoming  2021-12-10      Unknown  56.0             US  42.7560   
121369        Wyoming  2021-12-10      Janssen  56.0             US  42.7560   
121370        Wyoming  2021-12-10          All  56.0             US  42.7560   
121371        Wyoming  2021-12-10   Unassigned  56.0             US  42.7560   

           Long_  Doses_alloc  Doses_shipped  Doses_admin  Stage_One_Doses  \
0       -86.9023          NaN            NaN          NaN              NaN   
1       -86.9023          NaN            NaN          NaN              NaN   
2       -86.9023          NaN            NaN          NaN              NaN   
3       -86.9023          NaN            NaN          NaN              NaN   
4       -86.9023          NaN            NaN          NaN              NaN   
...          ...          ...            ...          ...              ...   
121367 -107.3025          NaN       368600.0     290399.0              NaN   
121368 -107.3025          NaN            0.0        582.0              NaN   
121369 -107.3025          NaN        45100.0      27233.0          24754.0   
121370 -107.3025          NaN       837205.0     654822.0         316040.0   
121371 -107.3025          NaN            0.0          0.0         291286.0   

        Stage_Two_Doses Combined_Key  
0                   NaN  Alabama, US  
1                   NaN  Alabama, US  
2                   NaN  Alabama, US  
3                   NaN  Alabama, US  
4                   NaN  Alabama, US  
...                 ...          ...  
121367         111726.0  Wyoming, US  
121368              NaN  Wyoming, US  
121369              NaN  Wyoming, US  
121370         247134.0  Wyoming, US  
121371           3466.0  Wyoming, US  

[121372 rows x 13 columns]

In [5]:
# Read the file and store in people_vaccinated
people_vaccinated = pd.read_csv("https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/vaccine_data/us_data/time_series/people_vaccinated_us_timeline.csv")

# Display the result
people_vaccinated

FIPS Province_State Country_Region        Date      Lat     Long_  \
0       1.0        Alabama             US  2020-12-10  32.3182  -86.9023   
1       1.0        Alabama             US  2020-12-11  32.3182  -86.9023   
2       1.0        Alabama             US  2020-12-12  32.3182  -86.9023   
3       1.0        Alabama             US  2020-12-13  32.3182  -86.9023   
4       1.0        Alabama             US  2020-12-14  32.3182  -86.9023   
...     ...            ...            ...         ...      ...       ...   
22267  56.0        Wyoming             US  2021-12-06  42.7560 -107.3025   
22268  56.0        Wyoming             US  2021-12-07  42.7560 -107.3025   
22269  56.0        Wyoming             US  2021-12-08  42.7560 -107.3025   
22270  56.0        Wyoming             US  2021-12-09  42.7560 -107.3025   
22271  56.0        Wyoming             US  2021-12-10  42.7560 -107.3025   

      Combined_Key  People_Fully_Vaccinated  People_Partially_Vaccinated  
0      Alabama, US                      NaN                          NaN  
1      Alabama, US                      NaN                          NaN  
2      Alabama, US                      NaN                          NaN  
3      Alabama, US                      NaN                          NaN  
4      Alabama, US                      NaN                          NaN  
...            ...                      ...                          ...  
22267  Wyoming, US                 266071.0                      47463.0  
22268  Wyoming, US                 267460.0                      47370.0  
22269  Wyoming, US                 267943.0                      47402.0  
22270  Wyoming, US                 268472.0                      47443.0  
22271  Wyoming, US                 268529.0                      47511.0  

[22272 rows x 9 columns]

In [6]:
# Read the file and store in testing
testing = pd.read_csv("https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/testing_data/time_series_covid19_US.csv")

# Display the result
testing

date state  cases_conf_probable  cases_confirmed  cases_probable  \
0        3/6/2020    AK                  NaN              NaN             NaN   
1        3/7/2020    AK                  NaN              NaN             NaN   
2        3/8/2020    AK                  NaN              NaN             NaN   
3        3/9/2020    AK                  NaN              NaN             NaN   
4       3/10/2020    AK                  NaN              NaN             NaN   
...           ...   ...                  ...              ...             ...   
36343  12/10/2021    VT              55057.0          53320.0          1737.0   
36344  12/10/2021    WA             790412.0         694617.0         95795.0   
36345  12/10/2021    WI            1024094.0         911568.0        112526.0   
36346  12/10/2021    WV             305418.0         237575.0         67843.0   
36347  12/10/2021    WY             112862.0          89364.0         23498.0   

       tests_viral_positive  tests_viral_negative  tests_viral_total  \
0                       NaN                   NaN                8.0   
1                       NaN                   NaN               12.0   
2                       NaN                   NaN               14.0   
3                       NaN                   NaN               23.0   
4                       NaN                   NaN               23.0   
...                     ...                   ...                ...   
36343                   NaN                   NaN          2676175.0   
36344              734205.0            10118939.0                NaN   
36345                   NaN                   NaN                NaN   
36346                   NaN                   NaN          4642045.0   
36347               60437.0             1081417.0          1168537.0   

       tests_antigen_positive  tests_antigen_total  people_viral_positive  \
0                         NaN                  NaN                    NaN   
1                         NaN                  NaN                    NaN   
2                         NaN                  NaN                    NaN   
3                         NaN                  NaN                    NaN   
4                         NaN                  NaN                    NaN   
...                       ...                  ...                    ...   
36343                     NaN                  NaN                53320.0   
36344                     NaN                  NaN               694617.0   
36345                     NaN                  NaN               911568.0   
36346                     NaN                  NaN               237575.0   
36347                     NaN                  NaN                89364.0   

       people_viral_total  people_antigen_positive  people_antigen_total  \
0                     NaN                      NaN                   NaN   
1                     NaN                      NaN                   NaN   
2                     NaN                      NaN                   NaN   
3                     NaN                      NaN                   NaN   
4                     NaN                      NaN                   NaN   
...                   ...                      ...                   ...   
36343            556105.0                      NaN                   NaN   
36344                 NaN                      NaN                   NaN   
36345           4623454.0                      NaN                   NaN   
36346                 NaN                      NaN                   NaN   
36347            260484.0                      NaN                   NaN   

       encounters_viral_total  tests_combined_total  
0                         NaN                   8.0  
1                         NaN                  12.0  
2                         NaN                  14.0  
3                         NaN                  23.0  
4                         NaN                  23.0  
...          

In [7]:
#Now we are using csvkit commands to load bulk data
#wget is used to load files
!wget https://raw.githubusercontent.com/pkbhatta5/GWU-DNSC-6305/main/cases.csv

--2021-12-12 00:11:09--  https://raw.githubusercontent.com/pkbhatta5/GWU-DNSC-6305/main/cases.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 78336 (76K) [text/plain]
Saving to: ‘cases.csv’

cases.csv           100%[===================>]  76.50K  --.-KB/s    in 0.001s  

2021-12-12 00:11:09 (72.1 MB/s) - ‘cases.csv’ saved [78336/78336]



In [8]:
# Create a new directory called "CSV"
!mkdir CSV

In [9]:
!wget -i cases.csv -P ./CSV/

--2021-12-12 00:11:10--  https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports_us/04-12-2020.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8566 (8.4K) [text/plain]
Saving to: ‘./CSV/04-12-2020.csv’

04-12-2020.csv      100%[===================>]   8.37K  --.-KB/s    in 0s      

2021-12-12 00:11:10 (79.5 MB/s) - ‘./CSV/04-12-2020.csv’ saved [8566/8566]

--2021-12-12 00:11:10--  https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports_us/04-13-2020.csv
Reusing existing connection to raw.githubusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 9353 (9.1K) [text/plain]
Saving to: ‘./CSV/04-13-2020.csv’

04-13-2020.csv  

In [10]:
# Get the current directory
!pwd

/home/ubuntu/notebooks


In [11]:
# Stack the files in CSV folder
!csvstack ./CSV/*.csv > cases_final.csv

In [12]:
!wc -l cases_final.csv

34703 cases_final.csv


In [13]:
# Backing up to the local storage using python commands

vaccine.to_csv("vaccine_backup.csv", index=False)
vaccine = pd.read_csv("vaccine_backup.csv")

people_vaccinated.to_csv("people_vaccinated_backup.csv", index=False)
people_vaccinated = pd.read_csv("people_vaccinated_backup.csv")

testing.to_csv("testing_backup.csv", index=False)
testing = pd.read_csv("testing_backup.csv")

testing.to_csv("cases_final_backup.csv", index=False)
cases= pd.read_csv('cases_final_backup.csv')

### Surveying the data

##### Exploring the vaccine data

In [14]:
# Looking at the datatypes in vaccine. We see that there are object and float type values
vaccine.dtypes

Province_State      object
Date                object
Vaccine_Type        object
FIPS               float64
Country_Region      object
Lat                float64
Long_              float64
Doses_alloc        float64
Doses_shipped      float64
Doses_admin        float64
Stage_One_Doses    float64
Stage_Two_Doses    float64
Combined_Key        object
dtype: object

In [15]:
# Displaying ten records from vacine
vaccine.head(10)

Province_State        Date Vaccine_Type  FIPS Country_Region      Lat  \
0        Alabama  2020-12-10          All   1.0             US  32.3182   
1        Alabama  2020-12-10      Moderna   1.0             US  32.3182   
2        Alabama  2020-12-10       Pfizer   1.0             US  32.3182   
3        Alabama  2020-12-11          All   1.0             US  32.3182   
4        Alabama  2020-12-11      Moderna   1.0             US  32.3182   
5        Alabama  2020-12-11       Pfizer   1.0             US  32.3182   
6        Alabama  2020-12-12          All   1.0             US  32.3182   
7        Alabama  2020-12-12      Moderna   1.0             US  32.3182   
8        Alabama  2020-12-12       Pfizer   1.0             US  32.3182   
9        Alabama  2020-12-13          All   1.0             US  32.3182   

     Long_  Doses_alloc  Doses_shipped  Doses_admin  Stage_One_Doses  \
0 -86.9023          NaN            NaN          NaN              NaN   
1 -86.9023          NaN            NaN          NaN              NaN   
2 -86.9023          NaN            NaN          NaN              NaN   
3 -86.9023          NaN            NaN          NaN              NaN   
4 -86.9023          NaN            NaN          NaN              NaN   
5 -86.9023          NaN            NaN          NaN              NaN   
6 -86.9023          NaN            NaN          NaN              NaN   
7 -86.9023          NaN            NaN          NaN              NaN   
8 -86.9023          NaN            NaN          NaN              NaN   
9 -86.9023          NaN            NaN          NaN              NaN   

   Stage_Two_Doses Combined_Key  
0              NaN  Alabama, US  
1              NaN  Alabama, US  
2              NaN  Alabama, US  
3              NaN  Alabama, US  
4              NaN  Alabama, US  
5              NaN  Alabama, US  
6              NaN  Alabama, US  
7              NaN  Alabama, US  
8              NaN  Alabama, US  
9              NaN  Alabama, US

In [16]:
# Displaying the column headers 
vaccine_columns = vaccine.columns
vaccine_columns

Index(['Province_State', 'Date', 'Vaccine_Type', 'FIPS', 'Country_Region',
       'Lat', 'Long_', 'Doses_alloc', 'Doses_shipped', 'Doses_admin',
       'Stage_One_Doses', 'Stage_Two_Doses', 'Combined_Key'],
      dtype='object')

In [17]:
# Looking into the startistical information about the vaccine data
vaccine.describe()

FIPS            Lat          Long_   Doses_alloc  \
count  110800.000000  110800.000000  110800.000000  1.667900e+04   
mean       32.540794      36.851425     -85.158753  1.912958e+06   
std        18.913326      10.794486      49.452982  4.724593e+06   
min         1.000000     -14.271000    -170.132000  0.000000e+00   
25%        17.000000      33.856900    -105.311100  3.120000e+04   
50%        32.000000      39.063900     -86.902300  1.848250e+05   
75%        47.000000      42.756000     -77.026800  1.131425e+06   
max        78.000000      61.370700     145.673900  2.751374e+07   

       Doses_shipped   Doses_admin  Stage_One_Doses  Stage_Two_Doses  
count   9.801600e+04  1.018620e+05     5.871900e+04     6.710800e+04  
mean    2.334918e+06  1.866385e+06     1.767667e+06     1.154575e+06  
std     5.201246e+06  4.276774e+06     3.318115e+06     2.108090e+06  
min    -1.860390e+05 -2.713460e+05    -1.538000e+03    -2.126800e+05  
25%     0.000000e+00  4.000000e+03     1.198765e+05     2.499625e+04  
50%     4.067700e+05  2.447000e+05     5.170790e+05     3.970140e+05  
75%     2.424180e+06  1.854106e+06     2.030548e+06     1.373673e+06  
max     7.267630e+07  6.196550e+07     3.173003e+07     2.387858e+07

In [18]:
#Explore vaccine data
vaccine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121372 entries, 0 to 121371
Data columns (total 13 columns):
 #   Column           Non-Null Count   Dtype  
---  ------           --------------   -----  
 0   Province_State   121372 non-null  object 
 1   Date             121372 non-null  object 
 2   Vaccine_Type     121372 non-null  object 
 3   FIPS             110800 non-null  float64
 4   Country_Region   121372 non-null  object 
 5   Lat              110800 non-null  float64
 6   Long_            110800 non-null  float64
 7   Doses_alloc      16679 non-null   float64
 8   Doses_shipped    98016 non-null   float64
 9   Doses_admin      101862 non-null  float64
 10  Stage_One_Doses  58719 non-null   float64
 11  Stage_Two_Doses  67108 non-null   float64
 12  Combined_Key     121372 non-null  object 
dtypes: float64(8), object(5)
memory usage: 12.0+ MB


In [19]:
#Count of rows in vaccine
len(vaccine)

121372

### People_vaccinated

In [20]:
#Data types in people_vaccinated data
people_vaccinated.dtypes

FIPS                           float64
Province_State                  object
Country_Region                  object
Date                            object
Lat                            float64
Long_                          float64
Combined_Key                    object
People_Fully_Vaccinated        float64
People_Partially_Vaccinated    float64
dtype: object

In [21]:
#First few rows in the dataset
people_vaccinated.head(10)

FIPS Province_State Country_Region        Date      Lat    Long_  \
0   1.0        Alabama             US  2020-12-10  32.3182 -86.9023   
1   1.0        Alabama             US  2020-12-11  32.3182 -86.9023   
2   1.0        Alabama             US  2020-12-12  32.3182 -86.9023   
3   1.0        Alabama             US  2020-12-13  32.3182 -86.9023   
4   1.0        Alabama             US  2020-12-14  32.3182 -86.9023   
5   1.0        Alabama             US  2020-12-15  32.3182 -86.9023   
6   1.0        Alabama             US  2020-12-16  32.3182 -86.9023   
7   1.0        Alabama             US  2020-12-17  32.3182 -86.9023   
8   1.0        Alabama             US  2020-12-18  32.3182 -86.9023   
9   1.0        Alabama             US  2020-12-19  32.3182 -86.9023   

  Combined_Key  People_Fully_Vaccinated  People_Partially_Vaccinated  
0  Alabama, US                      NaN                          NaN  
1  Alabama, US                      NaN                          NaN  
2  Alabama, US                      NaN                          NaN  
3  Alabama, US                      NaN                          NaN  
4  Alabama, US                      NaN                          NaN  
5  Alabama, US                      NaN                          NaN  
6  Alabama, US                      NaN                          NaN  
7  Alabama, US                      NaN                          NaN  
8  Alabama, US                      NaN                          NaN  
9  Alabama, US                      NaN                          NaN

In [22]:
#Columns in the dataset
people_vaccinated_columns = people_vaccinated.columns
people_vaccinated_columns

Index(['FIPS', 'Province_State', 'Country_Region', 'Date', 'Lat', 'Long_',
       'Combined_Key', 'People_Fully_Vaccinated',
       'People_Partially_Vaccinated'],
      dtype='object')

In [23]:
#Describing the dataset
people_vaccinated.describe()

FIPS           Lat         Long_  People_Fully_Vaccinated  \
count  20496.000000  20496.000000  20496.000000             1.991300e+04   
mean      32.535714     36.840089    -85.206614             2.158347e+06   
std       18.905264     10.789655     49.309415             3.285510e+06   
min        1.000000    -14.271000   -170.132000             0.000000e+00   
25%       17.750000     34.594600   -101.165775             2.966510e+05   
50%       31.500000     39.061850    -87.944200             1.001273e+06   
75%       46.250000     42.361650    -76.970625             2.697843e+06   
max       78.000000     61.370700    145.673900             2.610981e+07   

       People_Partially_Vaccinated  
count                 1.923100e+04  
mean                  5.323429e+05  
std                   8.241023e+05  
min                   1.515000e+03  
25%                   9.863650e+04  
50%                   2.846730e+05  
75%                   5.836815e+05  
max                   7.310293e+06

In [24]:
#Summary of data
people_vaccinated.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22272 entries, 0 to 22271
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   FIPS                         20496 non-null  float64
 1   Province_State               22272 non-null  object 
 2   Country_Region               22272 non-null  object 
 3   Date                         22272 non-null  object 
 4   Lat                          20496 non-null  float64
 5   Long_                        20496 non-null  float64
 6   Combined_Key                 22272 non-null  object 
 7   People_Fully_Vaccinated      19913 non-null  float64
 8   People_Partially_Vaccinated  19231 non-null  float64
dtypes: float64(5), object(4)
memory usage: 1.5+ MB


In [25]:
#Count of rows in dataset
len(people_vaccinated)

22272

### Testing

In [26]:
#Column data types
testing.dtypes

date                        object
state                       object
cases_conf_probable        float64
cases_confirmed            float64
cases_probable             float64
tests_viral_positive       float64
tests_viral_negative       float64
tests_viral_total          float64
tests_antigen_positive     float64
tests_antigen_total        float64
people_viral_positive      float64
people_viral_total         float64
people_antigen_positive    float64
people_antigen_total       float64
encounters_viral_total     float64
tests_combined_total       float64
dtype: object

In [27]:
#First few rows in dataset
testing.head(10)

date state  cases_conf_probable  cases_confirmed  cases_probable  \
0   3/6/2020    AK                  NaN              NaN             NaN   
1   3/7/2020    AK                  NaN              NaN             NaN   
2   3/8/2020    AK                  NaN              NaN             NaN   
3   3/9/2020    AK                  NaN              NaN             NaN   
4  3/10/2020    AK                  NaN              NaN             NaN   
5  3/11/2020    AK                  NaN              NaN             NaN   
6  3/12/2020    AK                  NaN              NaN             NaN   
7  3/13/2020    AK                  NaN              NaN             NaN   
8  3/14/2020    AK                  NaN              NaN             NaN   
9  3/15/2020    AK                  NaN              NaN             NaN   

   tests_viral_positive  tests_viral_negative  tests_viral_total  \
0                   NaN                   NaN                8.0   
1                   NaN                   NaN               12.0   
2                   NaN                   NaN               14.0   
3                   NaN                   NaN               23.0   
4                   NaN                   NaN               23.0   
5                   NaN                   NaN               46.0   
6                   NaN                   NaN               46.0   
7                   NaN                   NaN               60.0   
8                   NaN                   NaN              144.0   
9                   NaN                   NaN              144.0   

   tests_antigen_positive  tests_antigen_total  people_viral_positive  \
0                     NaN                  NaN                    NaN   
1                     NaN                  NaN                    NaN   
2                     NaN                  NaN                    NaN   
3                     NaN                  NaN                    NaN   
4                     NaN                  NaN                    NaN   
5                     NaN                  NaN                    NaN   
6                     NaN                  NaN                    NaN   
7                     NaN                  NaN                    NaN   
8                     NaN                  NaN                    NaN   
9                     NaN                  NaN                    NaN   

   people_viral_total  people_antigen_positive  people_antigen_total  \
0                 NaN                      NaN                   NaN   
1                 NaN                      NaN                   NaN   
2                 NaN                      NaN                   NaN   
3                 NaN                      NaN                   NaN   
4                 NaN                      NaN                   NaN   
5                 NaN                      NaN                   NaN   
6                 NaN                      NaN                   NaN   
7                 NaN                      NaN                   NaN   
8                 NaN                      NaN                   NaN   
9                 NaN                      NaN                   NaN   

   encounters_viral_total  tests_combined_total  
0                     NaN                   8.0  
1                     NaN                  12.0  
2                     NaN                  14.0  
3                     NaN                  23.0  
4                     NaN                  23.0  
5                     NaN                  46.0  
6                     NaN                  46.0  
7                     NaN                  60.0  
8                     NaN                 144.0  
9                     NaN                 144.0

In [28]:
#Columns in dataset
testing_columns = testing.columns
testing_columns

Index(['date', 'state', 'cases_conf_probable', 'cases_confirmed',
       'cases_probable', 'tests_viral_positive', 'tests_viral_negative',
       'tests_viral_total', 'tests_antigen_positive', 'tests_antigen_total',
       'people_viral_positive', 'people_viral_total',
       'people_antigen_positive', 'people_antigen_total',
       'encounters_viral_total', 'tests_combined_total'],
      dtype='object')

In [29]:
#Describing the dataset
testing.describe()

cases_conf_probable  cases_confirmed  cases_probable  \
count         3.604600e+04     1.367000e+04    13669.000000   
mean          3.816160e+05     6.216352e+05    66000.031531   
std           6.415302e+05     7.934100e+05   102746.873893   
min           0.000000e+00     0.000000e+00        0.000000   
25%           2.062425e+04     1.274668e+05        0.000000   
50%           1.330060e+05     3.982830e+05    17116.000000   
75%           4.740080e+05     7.538575e+05   105757.000000   
max           4.867604e+06     4.867604e+06   744042.000000   

       tests_viral_positive  tests_viral_negative  tests_viral_total  \
count          1.690100e+04          1.008000e+04       2.762600e+04   
mean           4.277679e+05          3.791567e+06       5.376051e+06   
std            6.682239e+05          5.441705e+06       1.017459e+07   
min            0.000000e+00          1.000000e+00       0.000000e+00   
25%            4.508300e+04          7.913925e+05       4.769302e+05   
50%            1.899060e+05          2.452230e+06       2.181484e+06   
75%            5.675730e+05          4.471633e+06       5.708713e+06   
max            4.382814e+06          3.993758e+07       1.140429e+08   

       tests_antigen_positive  tests_antigen_total  people_viral_positive  \
count             6238.000000         1.013700e+04           3.290600e+04   
mean             95709.072780         1.097295e+06           3.755736e+05   
std             101654.141462         1.304540e+06           6.227360e+05   
min                  0.000000         0.000000e+00           0.000000e+00   
25%              15266.500000         1.566980e+05           3.253225e+04   
50%              63009.500000         7.135160e+05           1.441490e+05   
75%             149922.000000         1.547758e+06           4.664005e+05   
max             544044.000000         9.443170e+06           4.867604e+06   

       people_viral_total  people_antigen_positive  people_antigen_total  \
count        1.607300e+04              1467.000000          2.145000e+03   
mean         1.725841e+06             63415.795501          4.077632e+05   
std          2.326857e+06             43717.742462          3.108861e+05   
min          1.000000e+00                 3.000000          3.000000e+00   
25%          2.546350e+05             27013.500000          1.581390e+05   
50%          8.120120e+05             65195.000000          3.513830e+05   
75%          2.313738e+06             87828.000000          5.803720e+05   
max          1.337491e+07            169280.000000          1.290571e+06   

       encounters_viral_total  tests_combined_total  
count            9.118000e+03          3.613700e+04  
mean             6.566187e+06          5.366615e+06  
std              1.161326e+07          1.056164e+07  
min              0.000000e+00          0.000000e+00  
25%              6.797435e+05          3.695960e+05  
50%              2.475578e+06          1.825164e+06  
75%              7.793231e+06          5.969026e+06  
max              8.280638e+07          1.140429e+08

In [30]:
#Summary of dataset
testing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36348 entries, 0 to 36347
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   date                     36348 non-null  object 
 1   state                    36348 non-null  object 
 2   cases_conf_probable      36046 non-null  float64
 3   cases_confirmed          13670 non-null  float64
 4   cases_probable           13669 non-null  float64
 5   tests_viral_positive     16901 non-null  float64
 6   tests_viral_negative     10080 non-null  float64
 7   tests_viral_total        27626 non-null  float64
 8   tests_antigen_positive   6238 non-null   float64
 9   tests_antigen_total      10137 non-null  float64
 10  people_viral_positive    32906 non-null  float64
 11  people_viral_total       16073 non-null  float64
 12  people_antigen_positive  1467 non-null   float64
 13  people_antigen_total     2145 non-null   float64
 14  encounters_viral_total

In [31]:
#Count of rows in dataset
len(testing)

36348

### Cases

In [32]:
#Data types in dataset
cases.dtypes

date                        object
state                       object
cases_conf_probable        float64
cases_confirmed            float64
cases_probable             float64
tests_viral_positive       float64
tests_viral_negative       float64
tests_viral_total          float64
tests_antigen_positive     float64
tests_antigen_total        float64
people_viral_positive      float64
people_viral_total         float64
people_antigen_positive    float64
people_antigen_total       float64
encounters_viral_total     float64
tests_combined_total       float64
dtype: object

In [33]:
#First few rows in dataset
cases.head(10)

date state  cases_conf_probable  cases_confirmed  cases_probable  \
0   3/6/2020    AK                  NaN              NaN             NaN   
1   3/7/2020    AK                  NaN              NaN             NaN   
2   3/8/2020    AK                  NaN              NaN             NaN   
3   3/9/2020    AK                  NaN              NaN             NaN   
4  3/10/2020    AK                  NaN              NaN             NaN   
5  3/11/2020    AK                  NaN              NaN             NaN   
6  3/12/2020    AK                  NaN              NaN             NaN   
7  3/13/2020    AK                  NaN              NaN             NaN   
8  3/14/2020    AK                  NaN              NaN             NaN   
9  3/15/2020    AK                  NaN              NaN             NaN   

   tests_viral_positive  tests_viral_negative  tests_viral_total  \
0                   NaN                   NaN                8.0   
1                   NaN                   NaN               12.0   
2                   NaN                   NaN               14.0   
3                   NaN                   NaN               23.0   
4                   NaN                   NaN               23.0   
5                   NaN                   NaN               46.0   
6                   NaN                   NaN               46.0   
7                   NaN                   NaN               60.0   
8                   NaN                   NaN              144.0   
9                   NaN                   NaN              144.0   

   tests_antigen_positive  tests_antigen_total  people_viral_positive  \
0                     NaN                  NaN                    NaN   
1                     NaN                  NaN                    NaN   
2                     NaN                  NaN                    NaN   
3                     NaN                  NaN                    NaN   
4                     NaN                  NaN                    NaN   
5                     NaN                  NaN                    NaN   
6                     NaN                  NaN                    NaN   
7                     NaN                  NaN                    NaN   
8                     NaN                  NaN                    NaN   
9                     NaN                  NaN                    NaN   

   people_viral_total  people_antigen_positive  people_antigen_total  \
0                 NaN                      NaN                   NaN   
1                 NaN                      NaN                   NaN   
2                 NaN                      NaN                   NaN   
3                 NaN                      NaN                   NaN   
4                 NaN                      NaN                   NaN   
5                 NaN                      NaN                   NaN   
6                 NaN                      NaN                   NaN   
7                 NaN                      NaN                   NaN   
8                 NaN                      NaN                   NaN   
9                 NaN                      NaN                   NaN   

   encounters_viral_total  tests_combined_total  
0                     NaN                   8.0  
1                     NaN                  12.0  
2                     NaN                  14.0  
3                     NaN                  23.0  
4                     NaN                  23.0  
5                     NaN                  46.0  
6                     NaN                  46.0  
7                     NaN                  60.0  
8                     NaN                 144.0  
9                     NaN                 144.0

In [34]:
#Columns in dataset 
cases_columns = cases.columns
cases_columns

Index(['date', 'state', 'cases_conf_probable', 'cases_confirmed',
       'cases_probable', 'tests_viral_positive', 'tests_viral_negative',
       'tests_viral_total', 'tests_antigen_positive', 'tests_antigen_total',
       'people_viral_positive', 'people_viral_total',
       'people_antigen_positive', 'people_antigen_total',
       'encounters_viral_total', 'tests_combined_total'],
      dtype='object')

In [35]:
#Describing the dataset
cases.describe()

cases_conf_probable  cases_confirmed  cases_probable  \
count         3.604600e+04     1.367000e+04    13669.000000   
mean          3.816160e+05     6.216352e+05    66000.031531   
std           6.415302e+05     7.934100e+05   102746.873893   
min           0.000000e+00     0.000000e+00        0.000000   
25%           2.062425e+04     1.274668e+05        0.000000   
50%           1.330060e+05     3.982830e+05    17116.000000   
75%           4.740080e+05     7.538575e+05   105757.000000   
max           4.867604e+06     4.867604e+06   744042.000000   

       tests_viral_positive  tests_viral_negative  tests_viral_total  \
count          1.690100e+04          1.008000e+04       2.762600e+04   
mean           4.277679e+05          3.791567e+06       5.376051e+06   
std            6.682239e+05          5.441705e+06       1.017459e+07   
min            0.000000e+00          1.000000e+00       0.000000e+00   
25%            4.508300e+04          7.913925e+05       4.769302e+05   
50%            1.899060e+05          2.452230e+06       2.181484e+06   
75%            5.675730e+05          4.471633e+06       5.708713e+06   
max            4.382814e+06          3.993758e+07       1.140429e+08   

       tests_antigen_positive  tests_antigen_total  people_viral_positive  \
count             6238.000000         1.013700e+04           3.290600e+04   
mean             95709.072780         1.097295e+06           3.755736e+05   
std             101654.141462         1.304540e+06           6.227360e+05   
min                  0.000000         0.000000e+00           0.000000e+00   
25%              15266.500000         1.566980e+05           3.253225e+04   
50%              63009.500000         7.135160e+05           1.441490e+05   
75%             149922.000000         1.547758e+06           4.664005e+05   
max             544044.000000         9.443170e+06           4.867604e+06   

       people_viral_total  people_antigen_positive  people_antigen_total  \
count        1.607300e+04              1467.000000          2.145000e+03   
mean         1.725841e+06             63415.795501          4.077632e+05   
std          2.326857e+06             43717.742462          3.108861e+05   
min          1.000000e+00                 3.000000          3.000000e+00   
25%          2.546350e+05             27013.500000          1.581390e+05   
50%          8.120120e+05             65195.000000          3.513830e+05   
75%          2.313738e+06             87828.000000          5.803720e+05   
max          1.337491e+07            169280.000000          1.290571e+06   

       encounters_viral_total  tests_combined_total  
count            9.118000e+03          3.613700e+04  
mean             6.566187e+06          5.366615e+06  
std              1.161326e+07          1.056164e+07  
min              0.000000e+00          0.000000e+00  
25%              6.797435e+05          3.695960e+05  
50%              2.475578e+06          1.825164e+06  
75%              7.793231e+06          5.969026e+06  
max              8.280638e+07          1.140429e+08

In [36]:
#Summary of dataset 
cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36348 entries, 0 to 36347
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   date                     36348 non-null  object 
 1   state                    36348 non-null  object 
 2   cases_conf_probable      36046 non-null  float64
 3   cases_confirmed          13670 non-null  float64
 4   cases_probable           13669 non-null  float64
 5   tests_viral_positive     16901 non-null  float64
 6   tests_viral_negative     10080 non-null  float64
 7   tests_viral_total        27626 non-null  float64
 8   tests_antigen_positive   6238 non-null   float64
 9   tests_antigen_total      10137 non-null  float64
 10  people_viral_positive    32906 non-null  float64
 11  people_viral_total       16073 non-null  float64
 12  people_antigen_positive  1467 non-null   float64
 13  people_antigen_total     2145 non-null   float64
 14  encounters_viral_total

In [37]:
#Count of rows in dataset
len(cases)

36348

# Ask 2: Surveying and wrangling
Acquire the data, survey it and wrangle it to suitable format.
You may use one or more of the following methods for acquiring and wrangling
the data
Unix command line tools (e.g. csvkit)
Relational databases
Spark
You may also use wrangling tool (e.g. Trifacta)
Describe any concerns with the data and changes you expect to overcome
Expectations: document your findings in the code. Make sure you describe each
step in a complete and concise manner

* Starting SQL, dropping existing database, creating new database and connecting to the database

In [38]:
%load_ext sql

In [39]:
!dropdb -U student week11

In [40]:
!createdb -U student week11

In [41]:
%sql postgresql://student@/week11

### Acquiring the required data files using Wget

Vaccine data:

In [42]:
!wget https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/vaccine_data/us_data/time_series/vaccine_data_us_timeline.csv

--2021-12-12 00:11:46--  https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/vaccine_data/us_data/time_series/vaccine_data_us_timeline.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10815775 (10M) [text/plain]
Saving to: ‘vaccine_data_us_timeline.csv’

vaccine_data_us_tim 100%[===================>]  10.31M  --.-KB/s    in 0.04s   

2021-12-12 00:11:46 (277 MB/s) - ‘vaccine_data_us_timeline.csv’ saved [10815775/10815775]



People vaccinated data: 

In [43]:
!wget https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/vaccine_data/us_data/time_series/people_vaccinated_us_timeline.csv

--2021-12-12 00:11:46--  https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/vaccine_data/us_data/time_series/people_vaccinated_us_timeline.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1649934 (1.6M) [text/plain]
Saving to: ‘people_vaccinated_us_timeline.csv’

people_vaccinated_u 100%[===================>]   1.57M  --.-KB/s    in 0.02s   

2021-12-12 00:11:47 (104 MB/s) - ‘people_vaccinated_us_timeline.csv’ saved [1649934/1649934]



Covid testing data: 

In [44]:
!wget https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/testing_data/time_series_covid19_US.csv

--2021-12-12 00:11:47--  https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/testing_data/time_series_covid19_US.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2328413 (2.2M) [text/plain]
Saving to: ‘time_series_covid19_US.csv’

time_series_covid19 100%[===================>]   2.22M  --.-KB/s    in 0.02s   

2021-12-12 00:11:47 (115 MB/s) - ‘time_series_covid19_US.csv’ saved [2328413/2328413]



* Note: Cases and Deaths data has already been fetched before.

### Creating table for vaccine_data_us_timeline.csv

In [45]:
!wc -l vaccine_data_us_timeline.csv

121373 vaccine_data_us_timeline.csv


In [46]:
!csvcut -n vaccine_data_us_timeline.csv

  1: Province_State
  2: Date
  3: Vaccine_Type
  4: FIPS
  5: Country_Region
  6: Lat
  7: Long_
  8: Doses_alloc
  9: Doses_shipped
 10: Doses_admin
 11: Stage_One_Doses
 12: Stage_Two_Doses
 13: Combined_Key


* Creating new table for vaccine

In [47]:
%%sql
DROP TABLE IF EXISTS vaccine;

CREATE TABLE vaccine (
    Province_state VARCHAR(64) NOT NULL,
    date DATE NOT NULL,
    vaccine_type VARCHAR(64) NOT NULL,
    FIPS VARCHAR(10) NULL,
    country_region VARCHAR(3) NOT NULL,
    lat FLOAT NULL,
    long FLOAT NULL,
    doses_alloc INTEGER NULL,
    doses_shipped INTEGER NULL,
    doses_admin INTEGER NULL,
    stage_one_doses INTEGER NULL,
    stage_two_doses INTEGER NULL,
    combined_key VARCHAR(64) NULL
)

 * postgresql://student@/week11
Done.
Done.


[]

* Check the table

In [48]:
%%sql
SELECT * from vaccine

 * postgresql://student@/week11
0 rows affected.


[]

* Display the current working directory

In [49]:
!pwd

/home/ubuntu/notebooks


* Copying the vaccine_data_us_timeline.csv file from mentioned path

In [50]:
%%sql
COPY vaccine FROM '/home/ubuntu/notebooks/vaccine_data_us_timeline.csv'
CSV
HEADER;

 * postgresql://student@/week11
121372 rows affected.


[]

* Display 5 records from the vaccine table

In [51]:
%%sql
SELECT * from vaccine limit 5

 * postgresql://student@/week11
5 rows affected.


[('Alabama', datetime.date(2020, 12, 10), 'All', '1', 'US', 32.3182, -86.9023, None, None, None, None, None, 'Alabama, US'),
 ('Alabama', datetime.date(2020, 12, 10), 'Moderna', '1', 'US', 32.3182, -86.9023, None, None, None, None, None, 'Alabama, US'),
 ('Alabama', datetime.date(2020, 12, 10), 'Pfizer', '1', 'US', 32.3182, -86.9023, None, None, None, None, None, 'Alabama, US'),
 ('Alabama', datetime.date(2020, 12, 11), 'All', '1', 'US', 32.3182, -86.9023, None, None, None, None, None, 'Alabama, US'),
 ('Alabama', datetime.date(2020, 12, 11), 'Moderna', '1', 'US', 32.3182, -86.9023, None, None, None, None, None, 'Alabama, US')]

* Count of rows in table

In [52]:
%%sql
SELECT COUNT(*) FROM vaccine;

 * postgresql://student@/week11
1 rows affected.


[(121372,)]

* Making the combination of FIPS, Date and vaccine type to make the combination as primary key in the next step

In [53]:
%%sql
SELECT distinct FIPS,date,vaccine_type, CONCAT(FIPS, ',', DATE, ',', vaccine_type) AS primary_key FROM VACCINE 
LIMIT 5

 * postgresql://student@/week11
5 rows affected.


[('39', datetime.date(2021, 8, 3), 'All', '39,2021-08-03,All'),
 ('66', datetime.date(2021, 1, 3), 'All', '66,2021-01-03,All'),
 ('8', datetime.date(2021, 5, 22), 'Unknown', '8,2021-05-22,Unknown'),
 ('46', datetime.date(2021, 9, 18), 'Janssen', '46,2021-09-18,Janssen'),
 ('10', datetime.date(2021, 3, 2), 'All', '10,2021-03-02,All')]

* Add primary key column

In [54]:
%%sql
ALTER TABLE vaccine ADD column primary_key varchar(50);

 * postgresql://student@/week11
Done.


[]

* Adding the concatenated data into column

In [55]:
%%sql
UPDATE vaccine
SET primary_key = CONCAT(FIPS, ',', DATE, ',', vaccine_type)

 * postgresql://student@/week11
121372 rows affected.


[]

* Display the 5 records

In [56]:
%%sql
SELECT * from vaccine limit 5

 * postgresql://student@/week11
5 rows affected.


[('Alabama', datetime.date(2020, 12, 10), 'All', '1', 'US', 32.3182, -86.9023, None, None, None, None, None, 'Alabama, US', '1,2020-12-10,All'),
 ('Alabama', datetime.date(2020, 12, 10), 'Moderna', '1', 'US', 32.3182, -86.9023, None, None, None, None, None, 'Alabama, US', '1,2020-12-10,Moderna'),
 ('Alabama', datetime.date(2020, 12, 10), 'Pfizer', '1', 'US', 32.3182, -86.9023, None, None, None, None, None, 'Alabama, US', '1,2020-12-10,Pfizer'),
 ('Alabama', datetime.date(2020, 12, 11), 'All', '1', 'US', 32.3182, -86.9023, None, None, None, None, None, 'Alabama, US', '1,2020-12-11,All'),
 ('Alabama', datetime.date(2020, 12, 11), 'Moderna', '1', 'US', 32.3182, -86.9023, None, None, None, None, None, 'Alabama, US', '1,2020-12-11,Moderna')]

* Checking duplicates

In [57]:
%%sql
select primary_key, count(*)
from vaccine
group by primary_key
order by count desc
limit 5

 * postgresql://student@/week11
5 rows affected.


[(',2021-03-19,Janssen', 9),
 (',2021-04-06,Janssen', 9),
 (',2021-03-17,Janssen', 9),
 (',2021-03-26,Janssen', 9),
 (',2021-04-03,Janssen', 9)]

* Eliminating the Null values for FIPS

In [58]:
%%sql
DELETE from vaccine where fips is null

 * postgresql://student@/week11
10572 rows affected.


[]

* Set the primary key for table

In [59]:
%%sql
ALTER TABLE vaccine ADD primary key(primary_key)

 * postgresql://student@/week11
Done.


[]

#### Creating table for people_vaccinated_us_timeline.csv

* Taking the word count from people_vaccinated_us_timeline.csv file

In [60]:
!wc -l people_vaccinated_us_timeline.csv

22273 people_vaccinated_us_timeline.csv


* Columns in data

In [61]:
!csvcut -n people_vaccinated_us_timeline.csv

  1: FIPS
  2: Province_State
  3: Country_Region
  4: Date
  5: Lat
  6: Long_
  7: Combined_Key
  8: People_Fully_Vaccinated
  9: People_Partially_Vaccinated


* Looking into the data closely using csvstat

In [62]:
!head -n 100 people_vaccinated_us_timeline.csv | csvstat

  1. "FIPS"

	Type of data:          Boolean
	Contains null values:  False
	Unique values:         1
	Most common values:    True (99x)

  2. "Province_State"

	Type of data:          Text
	Contains null values:  False
	Unique values:         1
	Longest value:         7 characters
	Most common values:    Alabama (99x)

  3. "Country_Region"

	Type of data:          Text
	Contains null values:  False
	Unique values:         1
	Longest value:         2 characters
	Most common values:    US (99x)

  4. "Date"

	Type of data:          Date
	Contains null values:  False
	Unique values:         99
	Smallest value:        2020-12-10
	Largest value:         2021-03-18
	Most common values:    2020-12-10 (1x)
	                       2020-12-11 (1x)
	                       2020-12-12 (1x)
	                       2020-12-13 (1x)
	                       2020-12-14 (1x)

  5. "Lat"

	Type of data:          Number
	Contains null values:  False
	Unique values:         1
	Smallest value:        32.3182

* Creating the table

In [63]:
%%sql
DROP TABLE IF EXISTS people_vaccinated;


CREATE TABLE people_vaccinated (
    FIPS VARCHAR(10) NULL,
    Province_state VARCHAR(64) NOT NULL, 
    country_region VARCHAR(3) NOT NULL,
    date DATE NOT NULL,    
    lat FLOAT NULL,
    long FLOAT NULL, 
    combined_key VARCHAR(64) NOT NULL, 
    people_fully_vaccinated INTEGER NULL,
    people_partially_vaccinated INTEGER NULL
    
)


 * postgresql://student@/week11
Done.
Done.


[]

* Check table

In [64]:
%%sql
SELECT * from people_vaccinated limit 5

 * postgresql://student@/week11
0 rows affected.


[]

* Copying people_vaccinated_us_timeline.csv file from the mentioned path

In [65]:
%%sql
COPY people_vaccinated FROM '/home/ubuntu/notebooks/people_vaccinated_us_timeline.csv'
CSV
HEADER;

 * postgresql://student@/week11
22272 rows affected.


[]

* Counting the number of rows

In [66]:
%%sql
SELECT COUNT(*) FROM people_vaccinated;

 * postgresql://student@/week11
1 rows affected.


[(22272,)]

* Checking table

In [67]:
%%sql
SELECT * FROM people_vaccinated limit 5

 * postgresql://student@/week11
5 rows affected.


[('1', 'Alabama', 'US', datetime.date(2020, 12, 10), 32.3182, -86.9023, 'Alabama, US', None, None),
 ('1', 'Alabama', 'US', datetime.date(2020, 12, 11), 32.3182, -86.9023, 'Alabama, US', None, None),
 ('1', 'Alabama', 'US', datetime.date(2020, 12, 12), 32.3182, -86.9023, 'Alabama, US', None, None),
 ('1', 'Alabama', 'US', datetime.date(2020, 12, 13), 32.3182, -86.9023, 'Alabama, US', None, None),
 ('1', 'Alabama', 'US', datetime.date(2020, 12, 14), 32.3182, -86.9023, 'Alabama, US', None, None)]

* Adding primary key column to the table using Alter command

In [68]:
%%sql
ALTER TABLE people_vaccinated ADD column primary_key varchar(30);

 * postgresql://student@/week11
Done.


[]

* Set primary key values as combination of fips and date values

In [69]:
%%sql
UPDATE people_vaccinated
SET primary_key = CONCAT(FIPS, ',', DATE)

 * postgresql://student@/week11
22272 rows affected.


[]

* Check table

In [70]:
%%sql
SELECT * from people_vaccinated limit 5

 * postgresql://student@/week11
5 rows affected.


[('1', 'Alabama', 'US', datetime.date(2020, 12, 10), 32.3182, -86.9023, 'Alabama, US', None, None, '1,2020-12-10'),
 ('1', 'Alabama', 'US', datetime.date(2020, 12, 11), 32.3182, -86.9023, 'Alabama, US', None, None, '1,2020-12-11'),
 ('1', 'Alabama', 'US', datetime.date(2020, 12, 12), 32.3182, -86.9023, 'Alabama, US', None, None, '1,2020-12-12'),
 ('1', 'Alabama', 'US', datetime.date(2020, 12, 13), 32.3182, -86.9023, 'Alabama, US', None, None, '1,2020-12-13'),
 ('1', 'Alabama', 'US', datetime.date(2020, 12, 14), 32.3182, -86.9023, 'Alabama, US', None, None, '1,2020-12-14')]

* Checking duplicates

In [71]:
%%sql
select primary_key, count(*)
from people_vaccinated
group by primary_key
order by count desc
limit 50

 * postgresql://student@/week11
50 rows affected.


[(',2021-09-14', 5),
 (',2021-02-04', 5),
 (',2021-02-24', 5),
 (',2021-01-26', 5),
 (',2020-12-13', 5),
 (',2021-02-23', 5),
 (',2021-10-14', 5),
 (',2021-07-17', 5),
 (',2021-07-20', 5),
 (',2021-06-08', 5),
 (',2021-09-13', 5),
 (',2021-07-21', 5),
 (',2021-04-29', 5),
 (',2021-01-29', 5),
 (',2021-02-01', 5),
 (',2021-03-03', 5),
 (',2021-08-30', 5),
 (',2021-07-15', 5),
 (',2021-04-28', 5),
 (',2021-07-10', 5),
 (',2020-12-12', 5),
 (',2021-08-22', 5),
 (',2021-02-21', 5),
 (',2021-01-31', 5),
 (',2021-06-30', 5),
 (',2021-03-12', 5),
 (',2020-12-10', 5),
 (',2021-05-08', 5),
 (',2021-06-02', 5),
 (',2021-07-26', 5),
 (',2021-04-14', 5),
 (',2021-01-07', 5),
 (',2021-08-28', 5),
 (',2021-06-12', 5),
 (',2021-05-17', 5),
 (',2020-12-28', 5),
 (',2021-10-10', 5),
 (',2021-02-15', 5),
 (',2021-09-21', 5),
 (',2021-01-18', 5),
 (',2021-03-01', 5),
 (',2021-05-29', 5),
 (',2021-05-09', 5),
 (',2021-04-07', 5),
 (',2021-09-25', 5),
 (',2021-05-16', 5),
 (',2021-04-20', 5),
 (',2021-08-19', 5),
 (',2021-09-22', 5),
 (',2021-04-21', 5)]

* Removing NULLs from people_vaccinated where FIPS is not given

In [72]:
%%sql
DELETE FROM people_vaccinated WHERE fips is null

 * postgresql://student@/week11
1776 rows affected.


[]

* Set primary key

In [73]:
%%sql
ALTER TABLE people_vaccinated ADD primary key(primary_key)

 * postgresql://student@/week11
Done.


[]

### Creating table for time_series_covid19_US.csv

* Taking word count of the time_series_covid19_us.csv file

In [74]:
!wc -l time_series_covid19_US.csv

36349 time_series_covid19_US.csv


* Check columns

In [75]:
!csvcut -n time_series_covid19_US.csv

  1: date
  2: state
  3: cases_conf_probable
  4: cases_confirmed
  5: cases_probable
  6: tests_viral_positive
  7: tests_viral_negative
  8: tests_viral_total
  9: tests_antigen_positive
 10: tests_antigen_total
 11: people_viral_positive
 12: people_viral_total
 13: people_antigen_positive
 14: people_antigen_total
 15: encounters_viral_total
 16: tests_combined_total


* Looking into the data of time_Series_covid19_us.csv file to see if the datatypes are correct or need an alter

In [76]:
!head -n 100 time_series_covid19_US.csv | csvstat

  1. "date"

	Type of data:          Date
	Contains null values:  False
	Unique values:         99
	Smallest value:        2020-03-06
	Largest value:         2020-06-12
	Most common values:    2020-03-06 (1x)
	                       2020-03-07 (1x)
	                       2020-03-08 (1x)
	                       2020-03-09 (1x)
	                       2020-03-10 (1x)

  2. "state"

	Type of data:          Text
	Contains null values:  False
	Unique values:         1
	Longest value:         2 characters
	Most common values:    AK (99x)

  3. "cases_conf_probable"

	Type of data:          Number
	Contains null values:  True (excluded from calculations)
	Unique values:         84
	Smallest value:        3
	Largest value:         630
	Sum:                   27941
	Mean:                  317.511364
	Median:                355
	StDev:                 157.007796
	Most common values:    None (11x)
	                       339 (2x)
	                       355 (2x)
	                       401 (2x)


* Creating a new table "tests" and converting columns which were previously declared as booleans into integer type

In [77]:
%%sql
DROP TABLE IF EXISTS tests;

CREATE TABLE tests (
    date DATE NOT NULL,
    state_code VARCHAR(3) NOT NULL, 
    cases_conf_probable INTEGER NULL,  
    cases_confirmed INTEGER NULL,
    cases_probable INTEGER NULL,  
    tests_viral_positive INTEGER NULL,
    tests_viral_negative INTEGER NULL, 
    tests_viral_total INTEGER NULL, 
    tests_antigen_positive INTEGER NULL,
    tests_antigen_total INTEGER NULL,
    people_viral_positive INTEGER NULL,
    people_viral_total INTEGER NULL,
    people_antigen_positive INTEGER NULL,
    people_antigen_total INTEGER NULL,
    encounters_viral_total INTEGER NULL,
    tests_combined_total INTEGER NULL
    
)

 * postgresql://student@/week11
Done.
Done.


[]

#### Specifics: 
- tests_viral_positive to int, tests_viral_negative to int, cases_confirmed to int, cases_probable to int, tests_antigen_positive to int
- tests_antigen_total to int, people_antigen_positive and people_antigen_total to int, people_viral_total to int, tests_viral_total to null 
- tests_combined_total to null, encounters_viral_total to int 

* Check table

In [78]:
%%sql
SELECT * from tests limit 5

 * postgresql://student@/week11
0 rows affected.


[]

* Copying time_series_covid19_us.csv file from the mentioned path

In [79]:
%%sql
COPY tests FROM '/home/ubuntu/notebooks/time_series_covid19_US.csv'
CSV
HEADER;

 * postgresql://student@/week11
36348 rows affected.


[]

* Check row count

In [80]:
%%sql
SELECT COUNT(*) FROM tests;

 * postgresql://student@/week11
1 rows affected.


[(36348,)]

* Check table

In [81]:
%%sql
SELECT * FROM tests
LIMIT 10

 * postgresql://student@/week11
10 rows affected.


[(datetime.date(2020, 3, 6), 'AK', None, None, None, None, None, 8, None, None, None, None, None, None, None, 8),
 (datetime.date(2020, 3, 7), 'AK', None, None, None, None, None, 12, None, None, None, None, None, None, None, 12),
 (datetime.date(2020, 3, 8), 'AK', None, None, None, None, None, 14, None, None, None, None, None, None, None, 14),
 (datetime.date(2020, 3, 9), 'AK', None, None, None, None, None, 23, None, None, None, None, None, None, None, 23),
 (datetime.date(2020, 3, 10), 'AK', None, None, None, None, None, 23, None, None, None, None, None, None, None, 23),
 (datetime.date(2020, 3, 11), 'AK', None, None, None, None, None, 46, None, None, None, None, None, None, None, 46),
 (datetime.date(2020, 3, 12), 'AK', None, None, None, None, None, 46, None, None, None, None, None, None, None, 46),
 (datetime.date(2020, 3, 13), 'AK', None, None, None, None, None, 60, None, None, None, None, None, None, None, 60),
 (datetime.date(2020, 3, 14), 'AK', None, None, None, None, None, 144, None, None, None, None, None, None, None, 144),
 (datetime.date(2020, 3, 15), 'AK', None, None, None, None, None, 144, None, None, None, None, None, None, None, 144)]

#### Create Mapping table for state codes and states


* We will be using this mapping table to merge with the test table and get codes for the states
* Creating mapping table

In [82]:
%%sql
DROP TABLE IF EXISTS mapping;

CREATE TABLE mapping (
    StateAbbrev   CHAR (2),
    fips          varchar(2),
    State         VARCHAR (32)
)

 * postgresql://student@/week11
Done.
Done.


[]

* Inserting values into table

In [83]:
%%sql
INSERT into mapping values 
('AL', '1','Alabama'),
('AK', '2', 'Alaska'),
('AZ',  '4','Arizona'),
('AR',  '5','Arkansas'),
('CA', '6', 'California'),
('CO',  '8','Colorado'),
('CT',  '9', 'Connecticut'),
('DE',  '10', 'Delaware'),
('DC', '11', 'District of Columbia'),
('FL',  '12','Florida'),
('GA','13', 'Georgia'),
('HI', '15', 'Hawaii'),
('ID', '16','Idaho'),
('IL', '17','Illinois'),
('IN','18', 'Indiana'),
('IA', '19','Iowa'),
('KS', '20','Kansas'),
('KY','21', 'Kentucky'),
('LA', '22','Louisiana'),
('ME','23', 'Maine'),
('MD', '24','Maryland'),
('MA', '25','Massachusetts'),
('MI', '26','Michigan'),
('MN','27', 'Minnesota'),
('MS','28', 'Mississippi'),
('MO', '29','Missouri'),
('MT','30', 'Montana'),
('NE', '31','Nebraska'),
('NV','32', 'Nevada'),
('NH', '33','New Hampshire'),
('NJ', '34','New Jersey'),
('NM','35', 'New Mexico'),
('NY','36', 'New York'),
('NC','37', 'North Carolina'),
('ND','38', 'North Dakota'),
('OH', '39','Ohio'),
('OK', '40','Oklahoma'),
('OR','41', 'Oregon'),
('PA', '42','Pennsylvania'),
('PR', '72','Puerto Rico'),
('RI','44', 'Rhode Island'),
('SC','45', 'South Carolina'),
('SD', '46','South Dakota'),
('TN', '47','Tennessee'),
('TX', '48','Texas'),
('UT','49', 'Utah'),
('VT', '50','Vermont'),
('VA', '51','Virginia'),
('WA', '53','Washington'),
('WV', '54','West Virginia'),
('WI', '55','Wisconsin'),
('WY','56', 'Wyoming'),
('AS','60', 'American Samoa'),
('GU','66', 'Guam'),
('MP','69', 'Northern Mariana Islands'),
('VI', '78', 'Virgin Islands')
;

 * postgresql://student@/week11
56 rows affected.


[]

* Check table

In [84]:
%%sql
SELECT * from mapping
limit 10;

 * postgresql://student@/week11
10 rows affected.


[('AL', '1', 'Alabama'),
 ('AK', '2', 'Alaska'),
 ('AZ', '4', 'Arizona'),
 ('AR', '5', 'Arkansas'),
 ('CA', '6', 'California'),
 ('CO', '8', 'Colorado'),
 ('CT', '9', 'Connecticut'),
 ('DE', '10', 'Delaware'),
 ('DC', '11', 'District of Columbia'),
 ('FL', '12', 'Florida')]

#### Merging Test with Mapping table

* Here we are joining the tests table with mapping table to create a new table "testing"
* Create a new table testing and pulling information from mapping and tests table by using LEFT JOIN

In [85]:
%%sql
DROP TABLE IF EXISTS testing;

CREATE TABLE testing AS (
SELECT tests.*, mapping.state, mapping.fips
FROM tests
LEFT JOIN mapping on tests.state_code = mapping.stateabbrev
)

 * postgresql://student@/week11
Done.
36348 rows affected.


[]

* Check table

In [86]:
%%sql
SELECT * from testing
limit 10

 * postgresql://student@/week11
10 rows affected.


[(datetime.date(2020, 3, 6), 'AK', None, None, None, None, None, 8, None, None, None, None, None, None, None, 8, 'Alaska', '2'),
 (datetime.date(2020, 3, 7), 'AK', None, None, None, None, None, 12, None, None, None, None, None, None, None, 12, 'Alaska', '2'),
 (datetime.date(2020, 3, 8), 'AK', None, None, None, None, None, 14, None, None, None, None, None, None, None, 14, 'Alaska', '2'),
 (datetime.date(2020, 3, 9), 'AK', None, None, None, None, None, 23, None, None, None, None, None, None, None, 23, 'Alaska', '2'),
 (datetime.date(2020, 3, 10), 'AK', None, None, None, None, None, 23, None, None, None, None, None, None, None, 23, 'Alaska', '2'),
 (datetime.date(2020, 3, 11), 'AK', None, None, None, None, None, 46, None, None, None, None, None, None, None, 46, 'Alaska', '2'),
 (datetime.date(2020, 3, 12), 'AK', None, None, None, None, None, 46, None, None, None, None, None, None, None, 46, 'Alaska', '2'),
 (datetime.date(2020, 3, 13), 'AK', None, None, None, None, None, 60, None, None, None, None, None, None, None, 60, 'Alaska', '2'),
 (datetime.date(2020, 3, 14), 'AK', None, None, None, None, None, 144, None, None, None, None, None, None, None, 144, 'Alaska', '2'),
 (datetime.date(2020, 3, 15), 'AK', None, None, None, None, None, 144, None, None, None, None, None, None, None, 144, 'Alaska', '2')]

#### Setting Primary Key for testing

* Add primary key column

In [87]:
%%sql
ALTER TABLE testing ADD column primary_key varchar(50);

 * postgresql://student@/week11
Done.


[]

* We concatenate FIPS and Date to build a unique column that can be set as a primary key

In [88]:
%%sql
UPDATE testing
SET primary_key = CONCAT(fips, ',', DATE)

 * postgresql://student@/week11
36348 rows affected.


[]

* Check table

In [89]:
%%sql
SELECT * from testing limit 5

 * postgresql://student@/week11
5 rows affected.


[(datetime.date(2020, 3, 7), 'ND', None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'North Dakota', '38', '38,2020-03-07'),
 (datetime.date(2020, 6, 29), 'VI', 81, None, None, None, None, None, None, None, 81, 2858, None, None, None, 2827, 'Virgin Islands', '78', '78,2020-06-29'),
 (datetime.date(2020, 6, 30), 'VI', 84, None, None, None, None, None, None, None, 84, 2907, None, None, None, 2903, 'Virgin Islands', '78', '78,2020-06-30'),
 (datetime.date(2021, 11, 22), 'AS', None, None, None, None, None, 2140, None, None, None, None, None, None, None, 2140, 'American Samoa', '60', '60,2021-11-22'),
 (datetime.date(2021, 11, 25), 'AL', 844594, 620863, 223731, None, None, 6262668, None, None, 620863, None, None, None, None, 6262668, 'Alabama', '1', '1,2021-11-25')]

* Checking if each value in the column primary_key has unique value

In [90]:
%%sql
select primary_key, count(*)
from testing
group by primary_key
order by count desc
limit 10

 * postgresql://student@/week11
10 rows affected.


[('26,2021-11-23', 1),
 ('20,2021-05-15', 1),
 ('45,2020-07-11', 1),
 ('37,2021-10-24', 1),
 ('37,2020-11-25', 1),
 ('21,2021-04-30', 1),
 ('25,2021-05-29', 1),
 ('42,2020-10-03', 1),
 ('49,2020-11-04', 1),
 ('16,2021-10-06', 1)]

* After confirming, we finally set the new column as primary key for testing

In [91]:
%%sql
ALTER TABLE testing ADD primary key(primary_key)

 * postgresql://student@/week11
Done.


[]

#### Creating table for cases_final.csv

* Word count of the cases_final.csv 

In [92]:
!wc -l cases_final.csv

34703 cases_final.csv


* Columns of data

In [93]:
!csvcut -n cases_final.csv

  1: Province_State
  2: Country_Region
  3: Last_Update
  4: Lat
  5: Long_
  6: Confirmed
  7: Deaths
  8: Recovered
  9: Active
 10: FIPS
 11: Incident_Rate
 12: Total_Test_Results
 13: People_Hospitalized
 14: Case_Fatality_Ratio
 15: UID
 16: ISO3
 17: Testing_Rate
 18: Hospitalization_Rate


* Looking into the data to analyze the datatypes and NULL values

In [94]:
!head -n 100 cases_final.csv | csvstat

  1. "Province_State"

	Type of data:          Text
	Contains null values:  False
	Unique values:         58
	Longest value:         24 characters
	Most common values:    Alabama (2x)
	                       Alaska (2x)
	                       American Samoa (2x)
	                       Arizona (2x)
	                       Arkansas (2x)

  2. "Country_Region"

	Type of data:          Text
	Contains null values:  False
	Unique values:         1
	Longest value:         2 characters
	Most common values:    US (99x)

  3. "Last_Update"

	Type of data:          DateTime
	Contains null values:  False
	Unique values:         2
	Smallest value:        2021-01-02 05:30:44
	Largest value:         2021-01-03 05:30:33
	Most common values:    2021-01-02 05:30:44 (58x)
	                       2021-01-03 05:30:33 (41x)

  4. "Lat"

	Type of data:          Number
	Contains null values:  True (excluded from calculations)
	Unique values:         57
	Smallest value:        -14.271
	Largest value:        

* Create table cases 

In [95]:
%%sql
DROP TABLE IF EXISTS cases;


CREATE TABLE cases (
    Province_State VARCHAR(24) NOT NULL,
    Country_Region VARCHAR(3) NOT NULL, 
    Last_Update DATE NULL,  
    Lat FLOAT NULL,
    Long FLOAT NULL,
    Confirmed INTEGER NOT NULL, 
    Deaths INTEGER NOT NULL,
    Recovered FLOAT NULL,
    Active FLOAT NULL, 
    Fips varchar(10) NULL, 
    Incident_Rate FLOAT NULL,
    Total_Test_Results FLOAT NULL,
    People_Hospitalized FLOAT NULL,
    Case_Fatality_Ratio FLOAT NULL,
    UID FLOAT NOT NULL,
    ISO3 VARCHAR(4) NOT NULL,
    Testing_Rate FLOAT NULL,
    Hospitalization_Rate FLOAT NULL
    
)

 * postgresql://student@/week11
Done.
Done.


[]

* Check table

In [96]:
%%sql
SELECT * from cases limit 5

 * postgresql://student@/week11
0 rows affected.


[]

* Copying cases from the mentioned path

In [97]:
%%sql
COPY cases FROM '/home/ubuntu/notebooks/cases_final.csv'
CSV
HEADER;

 * postgresql://student@/week11
34702 rows affected.


[]

* Check count of rows

In [98]:
%%sql
SELECT COUNT(*) FROM cases;

 * postgresql://student@/week11
1 rows affected.


[(34702,)]

* Check table

In [99]:
%%sql
SELECT * FROM cases
LIMIT 10

 * postgresql://student@/week11
10 rows affected.


[('Alabama', 'US', datetime.date(2021, 1, 2), 32.3182, -86.9023, 365747, 4872, 202137.0, 158738.0, '1.0', 7459.375895463867, 3275341.0, None, 1.3320683423240656, 84000001.0, 'USA', 66800.27369964625, None),
 ('Alaska', 'US', datetime.date(2021, 1, 2), 61.3707, -152.4044, 47019, 206, 7165.0, 39648.0, '2.0', 6427.355801762024, 1275750.0, None, 0.4381207596928901, 84000002.0, 'USA', 174391.1857780451, None),
 ('American Samoa', 'US', datetime.date(2021, 1, 2), -14.271, -170.132, 0, 0, None, None, '60.0', 0.0, 2140.0, None, None, 16.0, 'ASM', 3846.084721698028, None),
 ('Arizona', 'US', datetime.date(2021, 1, 2), 33.7298, -111.4312, 530267, 9015, 76934.0, 444318.0, '4.0', 7285.171274003372, 5155330.0, None, 1.7000869373353424, 84000004.0, 'USA', 39551.860582022906, None),
 ('Arkansas', 'US', datetime.date(2021, 1, 2), 34.9697, -92.3731, 229442, 3711, 199247.0, 26484.0, '5.0', 7602.945718144717, 2051488.0, None, 1.6174022192972517, 84000005.0, 'USA', 67979.49767446793, None),
 ('California', 'US', datetime.date(2021, 1, 2), 36.1162, -119.6816, 2437397, 26168, None, None, '6.0', 6168.716450096974, 33058311.0, None, 1.0736043410244618, 84000006.0, 'USA', 83666.03670970372, None),
 ('Colorado', 'US', datetime.date(2021, 1, 2), 39.0598, -105.3111, 337161, 4873, 18102.0, 314186.0, '8.0', 5854.774381044729, 4444206.0, None, 1.4453035790023163, 84000008.0, 'USA', 77173.28941628858, None),
 ('Connecticut', 'US', datetime.date(2021, 1, 2), 41.5978, -72.7554, 185708, 5995, 9800.0, 169913.0, '9.0', 5208.781228551867, 4320693.0, None, 3.2281861847631768, 84000009.0, 'USA', 121187.80339422885, None),
 ('Delaware', 'US', datetime.date(2021, 1, 2), 39.3185, -75.5071, 58064, 1065, 18851.0, 38148.0, '10.0', 5962.841099075341, 984606.0, None, 1.8341829705152934, 84000010.0, 'USA', 101113.41146314713, None),
 ('Diamond Princess', 'US', datetime.date(2021, 1, 2), None, None, 49, 0, None, None, '88888.0', None, None, None, 0.0, 84088888.0, 'USA', None, None)]

* Removing .0 from the FIPS values

In [100]:
%%sql
UPDATE cases
SET fips = replace(fips,'.0','')

 * postgresql://student@/week11
34702 rows affected.


[]

* Add new column primary key

In [101]:
%%sql
ALTER TABLE cases ADD column primary_key varchar(30);

 * postgresql://student@/week11
Done.


[]

* Setting primary key as the combination of FIPS and Last_update

In [102]:
%%sql
UPDATE cases
SET primary_key = CONCAT(FIPS, ',', LAST_UPDATE)

 * postgresql://student@/week11
34702 rows affected.


[]

* Check table

In [103]:
%%sql
SELECT * from cases limit 5

 * postgresql://student@/week11
5 rows affected.


[('Diamond Princess', 'US', datetime.date(2021, 1, 22), None, None, 49, 0, None, None, '88888', None, None, None, 0.0, 84088888.0, 'USA', None, None, '88888,2021-01-22'),
 ('Diamond Princess', 'US', datetime.date(2021, 1, 29), None, None, 49, 0, None, None, '88888', None, None, None, 0.0, 84088888.0, 'USA', None, None, '88888,2021-01-29'),
 ('Diamond Princess', 'US', datetime.date(2021, 1, 30), None, None, 49, 0, None, None, '88888', None, None, None, 0.0, 84088888.0, 'USA', None, None, '88888,2021-01-30'),
 ('Diamond Princess', 'US', datetime.date(2021, 1, 31), None, None, 49, 0, None, None, '88888', None, None, None, 0.0, 84088888.0, 'USA', None, None, '88888,2021-01-31'),
 ('Diamond Princess', 'US', datetime.date(2021, 2, 1), None, None, 49, 0, None, None, '88888', None, None, None, 0.0, 84088888.0, 'USA', None, None, '88888,2021-02-01')]

* Check duplicates

In [104]:
%%sql
select primary_key, count(*)
from cases
group by primary_key
order by count desc
limit 10

 * postgresql://student@/week11
10 rows affected.


[(',', 10),
 ('60,', 9),
 ('12,2020-04-14', 2),
 ('20,2021-05-15', 1),
 ('37,2021-10-24', 1),
 ('88888,2021-06-16', 1),
 ('37,2020-11-25', 1),
 ('25,2021-05-29', 1),
 ('42,2020-10-03', 1),
 ('21,2021-04-30', 1)]

* Removing values from the table where FIPS is not mentioned

In [105]:
%%sql
DELETE FROM cases WHERE fips is null

 * postgresql://student@/week11
19 rows affected.


[]

* Removing NULL values from last_update

In [106]:
%%sql
DELETE FROM cases WHERE last_update is null

 * postgresql://student@/week11
9 rows affected.


[]

* Deleting rows where FIPS is 12

In [107]:
%%sql
DELETE FROM cases WHERE fips='12'

 * postgresql://student@/week11
598 rows affected.


[]

* Adding the primary key

In [108]:
%%sql
ALTER TABLE cases ADD primary key(primary_key)

 * postgresql://student@/week11
Done.


[]

# Ask 5: Dimensional Database
Design a dimensional database to cover “Cases and Deaths”,
“Vaccinations” and “Testing” datasets (Daily and for U.S.). I expect that
your design will allow all other groups to answer most of their questions.
Be precise and document your design correctly
Expectation: A star schema diagram detailing the design. Would be nice to
produce an image of the design and added it to your code.

In [109]:
# Given below is the star schema for the COVID19 data using the tables we have created using the csv files. 
from IPython.display import Image
Image(url="https://github.com/pkbhatta5/GWU-DNSC-6305/blob/a1e3b2b48d9180bd7e37fd97345033ba728377bb/Star_Schema_Final.png?raw=true")

In the above diagram, there are 4 tables:
- Facts table is "merge" which contains the Foreign Keys.
- Dimension tables are "vaccine_dim", "day_dim"and  "state_dim".
The surrogate keys are vaccine_key, date_key and state_key. The Natural keys are vaccine_type, date and FIPS.

### Checking the tables for distinct date counts to get the highest range of dates

* We are looking for distinct date values in the vaccine table

In [110]:
%%sql
SELECT count (distinct date) from vaccine

 * postgresql://student@/week11
1 rows affected.


[(366,)]

* We are looking for distinct date values in the people_vaccinated table

In [111]:
%%sql
SELECT count (distinct date) from people_vaccinated

 * postgresql://student@/week11
1 rows affected.


[(366,)]

* We are looking for distinct date values in the testing table

In [112]:
%%sql
SELECT count (distinct date) from testing

 * postgresql://student@/week11
1 rows affected.


[(698,)]

* We are looking for distinct date values in the cases table

In [113]:
%%sql
SELECT count (distinct last_update) from cases

 * postgresql://student@/week11
1 rows affected.


[(598,)]

### Merging data

We have the star schema in place hence, we will now merge the tables to make a single  table from where we segregate the data and put them in Fact table and the three Dimension tables. Below are the 4 tables and their columns for reference.

In [114]:
%%sql
SELECT * from testing limit 1

 * postgresql://student@/week11
1 rows affected.


[(datetime.date(2020, 3, 7), 'ND', None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'North Dakota', '38', '38,2020-03-07')]

In [115]:
%%sql
SELECT * from cases limit 1

 * postgresql://student@/week11
1 rows affected.


[('Diamond Princess', 'US', datetime.date(2021, 1, 22), None, None, 49, 0, None, None, '88888', None, None, None, 0.0, 84088888.0, 'USA', None, None, '88888,2021-01-22')]

In [116]:
%%sql
SELECT * from vaccine limit 1

 * postgresql://student@/week11
1 rows affected.


[('Alabama', datetime.date(2020, 12, 10), 'All', '1', 'US', 32.3182, -86.9023, None, None, None, None, None, 'Alabama, US', '1,2020-12-10,All')]

In [117]:
%%sql
SELECT * from people_vaccinated limit 1

 * postgresql://student@/week11
1 rows affected.


[('1', 'Alabama', 'US', datetime.date(2020, 12, 10), 32.3182, -86.9023, 'Alabama, US', None, None, '1,2020-12-10')]

* Creating a merge table which has values from cases, vaccine, people_vaccinated and testing. We perform a FULL OUTER JOIN to create merge table to avoid loss of data.

In [118]:
%%sql
DROP TABLE IF EXISTS merge;

CREATE TABLE merge AS (
SELECT t.*, c.province_state, c.country_region, c.last_update, c.lat, c.long, 
       c.confirmed, c.deaths, c.recovered, c.active, c.fips as fips1, c.incident_rate, 
       c.total_test_results, c.people_hospitalized, c.case_fatality_ratio, c.uid, c.iso3, 
       c.testing_rate, c.hospitalization_rate, c.primary_key as primary_key1, 
       v.province_state as province_state1, v.date as date1, v.vaccine_type, v.fips as fips2, 
       v.country_region as country_region1, v.lat as lat1, v.long as long1, v.doses_alloc, v.doses_shipped, 
       v.doses_admin, v.stage_one_doses, v.stage_two_doses, v.combined_key, v.primary_key as primary_key2, p.fips as fips3,
       p.province_state as province_state2, p.country_region as country_region2, p.date as date2, p.lat as lat2, 
       p.long as long2, p.combined_key as combined_key1, p.people_fully_vaccinated, p.people_partially_vaccinated, 
       p.primary_key as primary_key3
from testing t
FULL OUTER JOIN cases c on t.state = c.province_state and t.date = c.last_update
FULL OUTER JOIN vaccine v on t.state = v.province_state and t.date = v.date
FULL OUTER JOIN people_vaccinated p on t.state = p.province_state and t.date = p.date
)

 * postgresql://student@/week11
Done.
127848 rows affected.


[]

* Check table

In [119]:
%%sql
select * from merge
limit 1

 * postgresql://student@/week11
1 rows affected.


[(datetime.date(2020, 3, 7), 'AL', 0, None, None, None, None, 402, None, None, 0, None, None, None, None, 402, 'Alabama', '1', '1,2020-03-07', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)]

* Checking duplicate values

In [120]:
%%sql
SELECT DISTINCT fips1, province_state
FROM merge
WHERE fips1 in ('999','888','99999','88888')

 * postgresql://student@/week11
4 rows affected.


[('888', 'Diamond Princess'),
 ('88888', 'Diamond Princess'),
 ('999', 'Grand Princess'),
 ('99999', 'Grand Princess')]

* We remove duplicate values (999, 888, 99999, 88888) of FIPS from merge to clean the table

In [121]:
%%sql
DELETE FROM merge
WHERE fips1 in ('999','888','99999','88888')

 * postgresql://student@/week11
1196 rows affected.


[]

#### Create state_dim table

* We create state_dim dimension table by selecting different columns from the merged table
* Checking all the unique values of states

In [122]:
%%sql
SELECT DISTINCT fips, state
FROM merge
UNION
SELECT DISTINCT fips1, province_state
FROM merge
UNION
SELECT DISTINCT fips2, province_state1
FROM merge
UNION
SELECT DISTINCT fips3, province_state2
FROM merge

 * postgresql://student@/week11
57 rows affected.


[(None, None),
 ('17', 'Illinois'),
 ('45', 'South Carolina'),
 ('12', 'Florida'),
 ('20', 'Kansas'),
 ('42', 'Pennsylvania'),
 ('11', 'District of Columbia'),
 ('78', 'Virgin Islands'),
 ('51', 'Virginia'),
 ('21', 'Kentucky'),
 ('16', 'Idaho'),
 ('40', 'Oklahoma'),
 ('25', 'Massachusetts'),
 ('30', 'Montana'),
 ('49', 'Utah'),
 ('32', 'Nevada'),
 ('1', 'Alabama'),
 ('18', 'Indiana'),
 ('41', 'Oregon'),
 ('72', 'Puerto Rico'),
 ('36', 'New York'),
 ('6', 'California'),
 ('34', 'New Jersey'),
 ('39', 'Ohio'),
 ('26', 'Michigan'),
 ('47', 'Tennessee'),
 ('53', 'Washington'),
 ('35', 'New Mexico'),
 ('55', 'Wisconsin'),
 ('10', 'Delaware'),
 ('60', 'American Samoa'),
 ('33', 'New Hampshire'),
 ('24', 'Maryland'),
 ('23', 'Maine'),
 ('46', 'South Dakota'),
 ('44', 'Rhode Island'),
 ('27', 'Minnesota'),
 ('5', 'Arkansas'),
 ('66', 'Guam'),
 ('8', 'Colorado'),
 ('50', 'Vermont'),
 ('69', 'Northern Mariana Islands'),
 ('31', 'Nebraska'),
 ('56', 'Wyoming'),
 ('38', 'North Dakota'),
 ('37', 'North Carolina'),
 ('54', 'West Virginia'),
 ('15', 'Hawaii'),
 ('28', 'Mississippi'),
 ('2', 'Alaska'),
 ('29', 'Missouri'),
 ('9', 'Connecticut'),
 ('19', 'Iowa'),
 ('22', 'Louisiana'),
 ('48', 'Texas'),
 ('13', 'Georgia'),
 ('4', 'Arizona')]

* Creating the state_dim table here 

In [123]:
%%sql
--ALTER TABLE merge DROP CONSTRAINT fk_state;
DROP TABLE IF EXISTS state_dim;

CREATE TABLE state_dim (
    state_key SERIAL PRIMARY KEY,
    fips varchar(8),
    state_US VARCHAR(64),
    state_code_US CHAR(2),
    lat FLOAT,
    long FLOAT
);

 * postgresql://student@/week11
Done.
Done.


[]

* Inserting values into the state_dim dimension table

In [124]:
%%sql
INSERT INTO state_dim (fips,state_US)
SELECT DISTINCT fips, state
FROM merge
UNION
SELECT DISTINCT fips1, province_state
FROM merge
UNION
SELECT DISTINCT fips2, province_state1
FROM merge
UNION
SELECT DISTINCT fips3, province_state2
FROM merge
order by state

 * postgresql://student@/week11
57 rows affected.


[]

* Check the table

In [125]:
%%sql
SELECT * from state_dim

 * postgresql://student@/week11
57 rows affected.


[(1, '1', 'Alabama', None, None, None),
 (2, '2', 'Alaska', None, None, None),
 (3, '60', 'American Samoa', None, None, None),
 (4, '4', 'Arizona', None, None, None),
 (5, '5', 'Arkansas', None, None, None),
 (6, '6', 'California', None, None, None),
 (7, '8', 'Colorado', None, None, None),
 (8, '9', 'Connecticut', None, None, None),
 (9, '10', 'Delaware', None, None, None),
 (10, '11', 'District of Columbia', None, None, None),
 (11, '12', 'Florida', None, None, None),
 (12, '13', 'Georgia', None, None, None),
 (13, '66', 'Guam', None, None, None),
 (14, '15', 'Hawaii', None, None, None),
 (15, '16', 'Idaho', None, None, None),
 (16, '17', 'Illinois', None, None, None),
 (17, '18', 'Indiana', None, None, None),
 (18, '19', 'Iowa', None, None, None),
 (19, '20', 'Kansas', None, None, None),
 (20, '21', 'Kentucky', None, None, None),
 (21, '22', 'Louisiana', None, None, None),
 (22, '23', 'Maine', None, None, None),
 (23, '24', 'Maryland', None, None, None),
 (24, '25', 'Massachusetts', None, None, None),
 (25, '26', 'Michigan', None, None, None),
 (26, '27', 'Minnesota', None, None, None),
 (27, '28', 'Mississippi', None, None, None),
 (28, '29', 'Missouri', None, None, None),
 (29, '30', 'Montana', None, None, None),
 (30, '31', 'Nebraska', None, None, None),
 (31, '32', 'Nevada', None, None, None),
 (32, '33', 'New Hampshire', None, None, None),
 (33, '34', 'New Jersey', None, None, None),
 (34, '35', 'New Mexico', None, None, None),
 (35, '36', 'New York', None, None, None),
 (36, '37', 'North Carolina', None, None, None),
 (37, '38', 'North Dakota', None, None, None),
 (38, '69', 'Northern Mariana Islands', None, None, None),
 (39, '39', 'Ohio', None, None, None),
 (40, '40', 'Oklahoma', None, None, None),
 (41, '41', 'Oregon', None, None, None),
 (42, '42', 'Pennsylvania', None, None, None),
 (43, '72', 'Puerto Rico', None, None, None),
 (44, '44', 'Rhode Island', None, None, None),
 (45, '45', 'South Carolina', None, None, None),
 (46, '46', 'South Dakota', None, None, None),
 (47, '47', 'Tennessee', None, None, None),
 (48, '48', 'Texas', None, None, None),
 (49, '49', 'Utah', None, None, None),
 (50, '50', 'Vermont', None, None, None),
 (51, '78', 'Virgin Islands', None, None, None),
 (52, '51', 'Virginia', None, None, None),
 (53, '53', 'Washington', None, None, None),
 (54, '54', 'West Virginia', None, None, None),
 (55, '55', 'Wisconsin', None, None, None),
 (56, '56', 'Wyoming', None, None, None),
 (57, None, None, None, None, None)]

* Removing rows where FIPS is NULL

In [126]:
%%sql
DELETE FROM state_dim where fips is null

 * postgresql://student@/week11
1 rows affected.


[]

* Check table

In [127]:
%%sql
SELECT * from state_dim

 * postgresql://student@/week11
56 rows affected.


[(1, '1', 'Alabama', None, None, None),
 (2, '2', 'Alaska', None, None, None),
 (3, '60', 'American Samoa', None, None, None),
 (4, '4', 'Arizona', None, None, None),
 (5, '5', 'Arkansas', None, None, None),
 (6, '6', 'California', None, None, None),
 (7, '8', 'Colorado', None, None, None),
 (8, '9', 'Connecticut', None, None, None),
 (9, '10', 'Delaware', None, None, None),
 (10, '11', 'District of Columbia', None, None, None),
 (11, '12', 'Florida', None, None, None),
 (12, '13', 'Georgia', None, None, None),
 (13, '66', 'Guam', None, None, None),
 (14, '15', 'Hawaii', None, None, None),
 (15, '16', 'Idaho', None, None, None),
 (16, '17', 'Illinois', None, None, None),
 (17, '18', 'Indiana', None, None, None),
 (18, '19', 'Iowa', None, None, None),
 (19, '20', 'Kansas', None, None, None),
 (20, '21', 'Kentucky', None, None, None),
 (21, '22', 'Louisiana', None, None, None),
 (22, '23', 'Maine', None, None, None),
 (23, '24', 'Maryland', None, None, None),
 (24, '25', 'Massachusetts', None, None, None),
 (25, '26', 'Michigan', None, None, None),
 (26, '27', 'Minnesota', None, None, None),
 (27, '28', 'Mississippi', None, None, None),
 (28, '29', 'Missouri', None, None, None),
 (29, '30', 'Montana', None, None, None),
 (30, '31', 'Nebraska', None, None, None),
 (31, '32', 'Nevada', None, None, None),
 (32, '33', 'New Hampshire', None, None, None),
 (33, '34', 'New Jersey', None, None, None),
 (34, '35', 'New Mexico', None, None, None),
 (35, '36', 'New York', None, None, None),
 (36, '37', 'North Carolina', None, None, None),
 (37, '38', 'North Dakota', None, None, None),
 (38, '69', 'Northern Mariana Islands', None, None, None),
 (39, '39', 'Ohio', None, None, None),
 (40, '40', 'Oklahoma', None, None, None),
 (41, '41', 'Oregon', None, None, None),
 (42, '42', 'Pennsylvania', None, None, None),
 (43, '72', 'Puerto Rico', None, None, None),
 (44, '44', 'Rhode Island', None, None, None),
 (45, '45', 'South Carolina', None, None, None),
 (46, '46', 'South Dakota', None, None, None),
 (47, '47', 'Tennessee', None, None, None),
 (48, '48', 'Texas', None, None, None),
 (49, '49', 'Utah', None, None, None),
 (50, '50', 'Vermont', None, None, None),
 (51, '78', 'Virgin Islands', None, None, None),
 (52, '51', 'Virginia', None, None, None),
 (53, '53', 'Washington', None, None, None),
 (54, '54', 'West Virginia', None, None, None),
 (55, '55', 'Wisconsin', None, None, None),
 (56, '56', 'Wyoming', None, None, None)]

* Creating a view to pull state_code and state values from merge table

In [128]:
%%sql
CREATE OR REPLACE VIEW view1 AS
SELECT DISTINCT state_code, state
FROM merge
where state_code is not null

 * postgresql://student@/week11
Done.


[]

* Check view 

In [129]:
%%sql
SELECT * from view1

 * postgresql://student@/week11
56 rows affected.


[('PA', 'Pennsylvania'),
 ('MP', 'Northern Mariana Islands'),
 ('OH', 'Ohio'),
 ('TN', 'Tennessee'),
 ('MS', 'Mississippi'),
 ('VI', 'Virgin Islands'),
 ('CT', 'Connecticut'),
 ('NM', 'New Mexico'),
 ('AS', 'American Samoa'),
 ('WV', 'West Virginia'),
 ('KS', 'Kansas'),
 ('HI', 'Hawaii'),
 ('GU', 'Guam'),
 ('IA', 'Iowa'),
 ('KY', 'Kentucky'),
 ('MO', 'Missouri'),
 ('RI', 'Rhode Island'),
 ('ND', 'North Dakota'),
 ('AZ', 'Arizona'),
 ('AK', 'Alaska'),
 ('MI', 'Michigan'),
 ('MD', 'Maryland'),
 ('OK', 'Oklahoma'),
 ('OR', 'Oregon'),
 ('ME', 'Maine'),
 ('MA', 'Massachusetts'),
 ('NC', 'North Carolina'),
 ('TX', 'Texas'),
 ('NH', 'New Hampshire'),
 ('IN', 'Indiana'),
 ('NJ', 'New Jersey'),
 ('WA', 'Washington'),
 ('PR', 'Puerto Rico'),
 ('UT', 'Utah'),
 ('LA', 'Louisiana'),
 ('DE', 'Delaware'),
 ('NE', 'Nebraska'),
 ('CO', 'Colorado'),
 ('NY', 'New York'),
 ('MT', 'Montana'),
 ('SD', 'South Dakota'),
 ('GA', 'Georgia'),
 ('WI', 'Wisconsin'),
 ('AR', 'Arkansas'),
 ('CA', 'California'),
 ('SC', 'South Carolina'),
 ('VA', 'Virginia'),
 ('ID', 'Idaho'),
 ('NV', 'Nevada'),
 ('DC', 'District of Columbia'),
 ('VT', 'Vermont'),
 ('WY', 'Wyoming'),
 ('AL', 'Alabama'),
 ('FL', 'Florida'),
 ('MN', 'Minnesota'),
 ('IL', 'Illinois')]

* Updating the state_dim table using the view created above

In [130]:
%%sql
UPDATE state_dim
SET state_code_us = view1.state_code
FROM view1
where view1.state=state_dim.state_us

 * postgresql://student@/week11
56 rows affected.


[]

* Check table

In [131]:
%%sql
SELECT * from state_dim
limit 10

 * postgresql://student@/week11
10 rows affected.


[(42, '42', 'Pennsylvania', 'PA', None, None),
 (38, '69', 'Northern Mariana Islands', 'MP', None, None),
 (39, '39', 'Ohio', 'OH', None, None),
 (47, '47', 'Tennessee', 'TN', None, None),
 (27, '28', 'Mississippi', 'MS', None, None),
 (51, '78', 'Virgin Islands', 'VI', None, None),
 (8, '9', 'Connecticut', 'CT', None, None),
 (34, '35', 'New Mexico', 'NM', None, None),
 (3, '60', 'American Samoa', 'AS', None, None),
 (54, '54', 'West Virginia', 'WV', None, None)]

* Creating another view as view2 to get the lat, long and province_state

In [132]:
%%sql
CREATE OR REPLACE VIEW view2 AS (
SELECT DISTINCT lat, long, province_state
FROM merge
UNION
SELECT DISTINCT lat1, long1, province_state1
FROM merge
UNION
SELECT DISTINCT lat2, long2, province_state2
FROM merge
)

 * postgresql://student@/week11
Done.


[]

* Check table

In [133]:
%%sql
SELECT * from view2
limit 2

 * postgresql://student@/week11
2 rows affected.


[(None, None, None), (18.3358, -64.8963, 'Virgin Islands')]

* Update the state_dim table and add the columns from view 2

In [134]:
%%sql
UPDATE state_dim
SET lat = view2.lat
FROM view2
WHERE view2.province_state = state_dim.state_us

 * postgresql://student@/week11
56 rows affected.


[]

* Update the rows in the above column created

In [135]:
%%sql
UPDATE state_dim
SET long = view2.long
FROM view2
WHERE view2.province_state = state_dim.state_us

 * postgresql://student@/week11
56 rows affected.


[]

### Dimension table - state_dim final 

In [136]:
%%sql
SELECT * from state_dim
order by state_us
limit 5

 * postgresql://student@/week11
5 rows affected.


[(1, '1', 'Alabama', 'AL', 32.3182, -86.9023),
 (2, '2', 'Alaska', 'AK', 61.3707, -152.4044),
 (3, '60', 'American Samoa', 'AS', -14.271, -170.132),
 (4, '4', 'Arizona', 'AZ', 33.7298, -111.4312),
 (5, '5', 'Arkansas', 'AR', 34.9697, -92.3731)]

* Adding constraints to the Merge table and declaring the Foreign key

In [137]:
%%sql
ALTER TABLE merge
ADD COLUMN state_key INTEGER,
ADD CONSTRAINT fk_state
    FOREIGN KEY (state_key)
    REFERENCES state_dim (state_key);

 * postgresql://student@/week11
Done.


[]

* Updating the state_key in the merge table

In [138]:
%%sql
UPDATE merge
SET state_key = state_dim.state_key
FROM state_dim
where merge.fips=state_dim.fips or merge.fips1=state_dim.fips or merge.fips2=state_dim.fips or merge.fips3=state_dim.fips

 * postgresql://student@/week11
126652 rows affected.


[]

* Check the table

In [139]:
%%sql
SELECT * from merge
limit 5

 * postgresql://student@/week11
5 rows affected.


[(datetime.date(2020, 3, 7), 'AL', 0, None, None, None, None, 402, None, None, 0, None, None, None, None, 402, 'Alabama', '1', '1,2020-03-07', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 1),
 (datetime.date(2020, 3, 30), 'AK', 118, None, None, None, None, 3654, None, None, 118, None, None, None, None, 3654, 'Alaska', '2', '2,2020-03-30', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 2),
 (datetime.date(2020, 11, 17), 'AK', 23874, None, None, 28361, 849757, 878622, None, None, 23874, None, None, None, None, 878622, 'Alaska', '2', '2,2020-11-17', 'Alaska', 'US', datetime.date(2020, 11, 17), 61.3707, -152.4044, 24414, 100, 7165.0, 17149.0, '2', 3337.3203288929594, 872347.0, None, 0.40960104857868435, 84000002.0, 'USA', 119247.20967267905, None, '2,2020-11-17', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 2),
 (datetime.date(2021, 4, 11), 'AK', 64782, 64782, 0, 74611, 1888767, 1966048, None, None, 64782, None, None, None, None, 1966048, 'Alaska', '2', '2,2021-04-11', 'Alaska', 'US', datetime.date(2021, 4, 11), 61.3707, -152.4044, 64782, 313, None, None, '2', 8855.504446069619, 1966048.0, None, 0.4831589021641814, 84000002.0, 'USA', 268752.8450061172, None, '2,2021-04-11', 'Alaska', datetime.date(2021, 4, 11), 'Unknown', '2', 'US', 61.3707, -152.4044, None, 0, 306, None, None, 'Alaska, US', '2,2021-04-11,Unknown', '2', 'Alaska', 'US', datetime.date(2021, 4, 11), 61.3707, -152.4044, 'Alaska, US', 203259, 72046, '2,2021-04-11', 2),
 (datetime.date(2021, 4, 18), 'AK', 65921, 65921, 0, 75886, 1930980, 2009651, None, None, 65921, None, None, None, None, 2009651, 'Alaska', '2', '2,2021-04-18', 'Alaska', 'US', datetime.date(2021, 4, 18), 61.3707, -152.4044, 65921, 334, None, None, '2', 9011.202318380962, 2009651.0, None, 0.5066670711912744, 84000002.0, 'USA', 274713.24388793577, None, '2,2021-04-18', 'Alaska', datetime.date(2021, 4, 18), 'Unknown', '2', 'US', 61.3707, -152.4044, None, 0, 72, None, None, 'Alaska, US', '2,2021-04-18,Unknown', '2', 'Alaska', 'US', datetime.date(2021, 4, 18), 61.3707, -152.4044, 'Alaska, US', 234735, 55950, '2,2021-04-18', 2)]

#### Dropping dimension columns from fact table

In [140]:
%%sql
ALTER TABLE merge
DROP COLUMN state_code CASCADE,
DROP COLUMN state,
DROP COLUMN fips,
DROP COLUMN province_state CASCADE,
DROP COLUMN country_region,
DROP COLUMN lat,
DROP COLUMN long,
DROP COLUMN fips1,
DROP COLUMN province_state1,
DROP COLUMN fips2,
DROP COLUMN country_region1,
DROP COLUMN lat1,
DROP COLUMN long1,
DROP COLUMN fips3,
DROP COLUMN province_state2,
DROP COLUMN country_region2,
DROP COLUMN lat2,
DROP COLUMN long2

 * postgresql://student@/week11
Done.


[]

* Check table

In [141]:
%%sql
SELECT * from merge
limit 5

 * postgresql://student@/week11
5 rows affected.


[(datetime.date(2021, 4, 11), 64782, 64782, 0, 74611, 1888767, 1966048, None, None, 64782, None, None, None, None, 1966048, '2,2021-04-11', datetime.date(2021, 4, 11), 64782, 313, None, None, 8855.504446069619, 1966048.0, None, 0.4831589021641814, 84000002.0, 'USA', 268752.8450061172, None, '2,2021-04-11', datetime.date(2021, 4, 11), 'Unknown', None, 0, 306, None, None, 'Alaska, US', '2,2021-04-11,Unknown', datetime.date(2021, 4, 11), 'Alaska, US', 203259, 72046, '2,2021-04-11', 2),
 (datetime.date(2021, 4, 18), 65921, 65921, 0, 75886, 1930980, 2009651, None, None, 65921, None, None, None, None, 2009651, '2,2021-04-18', datetime.date(2021, 4, 18), 65921, 334, None, None, 9011.202318380962, 2009651.0, None, 0.5066670711912744, 84000002.0, 'USA', 274713.24388793577, None, '2,2021-04-18', datetime.date(2021, 4, 18), 'Unknown', None, 0, 72, None, None, 'Alaska, US', '2,2021-04-18,Unknown', datetime.date(2021, 4, 18), 'Alaska, US', 234735, 55950, '2,2021-04-18', 2),
 (datetime.date(2021, 4, 25), 67059, 67059, 0, 77171, 1972943, 2053055, None, None, 67059, None, None, None, None, 2053055, '2,2021-04-25', datetime.date(2021, 4, 25), 67059, 334, None, None, 9166.763493701686, 2053055.0, None, 0.4980688647310577, 84000002.0, 'USA', 280646.4400686219, None, '2,2021-04-25', datetime.date(2021, 4, 25), 'Unknown', None, 0, 77, None, None, 'Alaska, US', '2,2021-04-25,Unknown', datetime.date(2021, 4, 25), 'Alaska, US', 251843, 51923, '2,2021-04-25', 2),
 (datetime.date(2021, 5, 2), 68148, 68148, 0, 78329, 2018707, 2100065, None, None, 68148, None, None, None, None, 2100065, '2,2021-05-02', datetime.date(2021, 5, 2), 68148, 347, None, None, 9315.62651648224, 2100065.0, None, 0.5091858895345425, 84000002.0, 'USA', 287072.56559746835, None, '2,2021-05-02', datetime.date(2021, 5, 2), 'Unknown', None, 0, 77, None, None, 'Alaska, US', '2,2021-05-02,Unknown', datetime.date(2021, 5, 2), 'Alaska, US', 263330, 45132, '2,2021-05-02', 2),
 (datetime.date(2021, 5, 9), 68880, 68880, 0, 79149, 2059510, 2141739, None, None, 68880, None, None, None, None, 2141739, '2,2021-05-09', datetime.date(2021, 5, 9), 68880, 349, None, None, 9415.68871361297, 2141739.0, None, 0.506678281068525, 84000002.0, 'USA', 292769.27598438924, None, '2,2021-05-09', datetime.date(2021, 5, 9), 'Unknown', None, 0, 83, None, None, 'Alaska, US', '2,2021-05-09,Unknown', datetime.date(2021, 5, 9), 'Alaska, US', 288320, 44130, '2,2021-05-09', 2)]

### Create vaccine table

* Check unique values

In [142]:
%%sql
SELECT DISTINCT vaccine_type
FROM merge

 * postgresql://student@/week11
8 rows affected.


[(None,),
 ('Pfizer',),
 ('Unknown',),
 ('Janssen',),
 ('unknown',),
 ('All',),
 ('Unassigned',),
 ('Moderna',)]

* Update the values to clean typographical error

In [143]:
%%sql
UPDATE merge
SET vaccine_type = REPLACE(vaccine_type, 'unknown', 'Unknown')

 * postgresql://student@/week11
126652 rows affected.


[]

* Check distinct values

In [144]:
%%sql
SELECT DISTINCT vaccine_type
FROM merge

 * postgresql://student@/week11
7 rows affected.


[(None,),
 ('Pfizer',),
 ('Unknown',),
 ('Janssen',),
 ('All',),
 ('Unassigned',),
 ('Moderna',)]

* Create new table

In [145]:
%%sql
--ALTER TABLE merge DROP CONSTRAINT fk_vaccine;
DROP TABLE IF EXISTS vaccine_dim;

CREATE TABLE vaccine_dim (
    vaccine_key SERIAL PRIMARY KEY,
    vaccine_type VARCHAR(10)
)

 * postgresql://student@/week11
Done.
Done.


[]

* Insert values into table

In [146]:
%%sql
INSERT INTO vaccine_dim (vaccine_type)
SELECT DISTINCT vaccine_type
FROM merge
order by vaccine_type

 * postgresql://student@/week11
7 rows affected.


[]

#### Dimension table - vaccine_dim final

In [147]:
%%sql
SELECT * from vaccine_dim

 * postgresql://student@/week11
7 rows affected.


[(1, 'All'),
 (2, 'Janssen'),
 (3, 'Moderna'),
 (4, 'Pfizer'),
 (5, 'Unassigned'),
 (6, 'Unknown'),
 (7, None)]

* Adding constraints to the merge table and decalring the foreign_key

In [148]:
%%sql
ALTER TABLE merge
ADD COLUMN vaccine_key INTEGER,
ADD CONSTRAINT fk_vaccine
    FOREIGN KEY(vaccine_key)
    REFERENCES vaccine_dim(vaccine_key);

 * postgresql://student@/week11
Done.


[]

* Updating the merge table to get the foreign key values in place

In [149]:
%%sql
UPDATE merge
SET vaccine_key = vaccine_dim.vaccine_key
FROM vaccine_dim
WHERE merge.vaccine_type = vaccine_dim.vaccine_type

 * postgresql://student@/week11
110800 rows affected.


[]

* Check table

In [150]:
%%sql
SELECT * from merge
limit 5

 * postgresql://student@/week11
5 rows affected.


[(datetime.date(2021, 4, 11), 64782, 64782, 0, 74611, 1888767, 1966048, None, None, 64782, None, None, None, None, 1966048, '2,2021-04-11', datetime.date(2021, 4, 11), 64782, 313, None, None, 8855.504446069619, 1966048.0, None, 0.4831589021641814, 84000002.0, 'USA', 268752.8450061172, None, '2,2021-04-11', datetime.date(2021, 4, 11), 'Unknown', None, 0, 306, None, None, 'Alaska, US', '2,2021-04-11,Unknown', datetime.date(2021, 4, 11), 'Alaska, US', 203259, 72046, '2,2021-04-11', 2, 6),
 (datetime.date(2021, 4, 18), 65921, 65921, 0, 75886, 1930980, 2009651, None, None, 65921, None, None, None, None, 2009651, '2,2021-04-18', datetime.date(2021, 4, 18), 65921, 334, None, None, 9011.202318380962, 2009651.0, None, 0.5066670711912744, 84000002.0, 'USA', 274713.24388793577, None, '2,2021-04-18', datetime.date(2021, 4, 18), 'Unknown', None, 0, 72, None, None, 'Alaska, US', '2,2021-04-18,Unknown', datetime.date(2021, 4, 18), 'Alaska, US', 234735, 55950, '2,2021-04-18', 2, 6),
 (datetime.date(2021, 4, 25), 67059, 67059, 0, 77171, 1972943, 2053055, None, None, 67059, None, None, None, None, 2053055, '2,2021-04-25', datetime.date(2021, 4, 25), 67059, 334, None, None, 9166.763493701686, 2053055.0, None, 0.4980688647310577, 84000002.0, 'USA', 280646.4400686219, None, '2,2021-04-25', datetime.date(2021, 4, 25), 'Unknown', None, 0, 77, None, None, 'Alaska, US', '2,2021-04-25,Unknown', datetime.date(2021, 4, 25), 'Alaska, US', 251843, 51923, '2,2021-04-25', 2, 6),
 (datetime.date(2021, 5, 2), 68148, 68148, 0, 78329, 2018707, 2100065, None, None, 68148, None, None, None, None, 2100065, '2,2021-05-02', datetime.date(2021, 5, 2), 68148, 347, None, None, 9315.62651648224, 2100065.0, None, 0.5091858895345425, 84000002.0, 'USA', 287072.56559746835, None, '2,2021-05-02', datetime.date(2021, 5, 2), 'Unknown', None, 0, 77, None, None, 'Alaska, US', '2,2021-05-02,Unknown', datetime.date(2021, 5, 2), 'Alaska, US', 263330, 45132, '2,2021-05-02', 2, 6),
 (datetime.date(2021, 5, 9), 68880, 68880, 0, 79149, 2059510, 2141739, None, None, 68880, None, None, None, None, 2141739, '2,2021-05-09', datetime.date(2021, 5, 9), 68880, 349, None, None, 9415.68871361297, 2141739.0, None, 0.506678281068525, 84000002.0, 'USA', 292769.27598438924, None, '2,2021-05-09', datetime.date(2021, 5, 9), 'Unknown', None, 0, 83, None, None, 'Alaska, US', '2,2021-05-09,Unknown', datetime.date(2021, 5, 9), 'Alaska, US', 288320, 44130, '2,2021-05-09', 2, 6)]

### Dropping dimension column from fact table

* We drop the vaccine_type column from merge since we have used this in vaccine dimension table

In [151]:
%%sql
ALTER TABLE merge
DROP COLUMN vaccine_type

 * postgresql://student@/week11
Done.


[]

* Check table

In [152]:
%%sql
SELECT * from merge
limit 5

 * postgresql://student@/week11
5 rows affected.


[(datetime.date(2021, 4, 11), 64782, 64782, 0, 74611, 1888767, 1966048, None, None, 64782, None, None, None, None, 1966048, '2,2021-04-11', datetime.date(2021, 4, 11), 64782, 313, None, None, 8855.504446069619, 1966048.0, None, 0.4831589021641814, 84000002.0, 'USA', 268752.8450061172, None, '2,2021-04-11', datetime.date(2021, 4, 11), None, 0, 306, None, None, 'Alaska, US', '2,2021-04-11,Unknown', datetime.date(2021, 4, 11), 'Alaska, US', 203259, 72046, '2,2021-04-11', 2, 6),
 (datetime.date(2021, 4, 18), 65921, 65921, 0, 75886, 1930980, 2009651, None, None, 65921, None, None, None, None, 2009651, '2,2021-04-18', datetime.date(2021, 4, 18), 65921, 334, None, None, 9011.202318380962, 2009651.0, None, 0.5066670711912744, 84000002.0, 'USA', 274713.24388793577, None, '2,2021-04-18', datetime.date(2021, 4, 18), None, 0, 72, None, None, 'Alaska, US', '2,2021-04-18,Unknown', datetime.date(2021, 4, 18), 'Alaska, US', 234735, 55950, '2,2021-04-18', 2, 6),
 (datetime.date(2021, 4, 25), 67059, 67059, 0, 77171, 1972943, 2053055, None, None, 67059, None, None, None, None, 2053055, '2,2021-04-25', datetime.date(2021, 4, 25), 67059, 334, None, None, 9166.763493701686, 2053055.0, None, 0.4980688647310577, 84000002.0, 'USA', 280646.4400686219, None, '2,2021-04-25', datetime.date(2021, 4, 25), None, 0, 77, None, None, 'Alaska, US', '2,2021-04-25,Unknown', datetime.date(2021, 4, 25), 'Alaska, US', 251843, 51923, '2,2021-04-25', 2, 6),
 (datetime.date(2021, 5, 2), 68148, 68148, 0, 78329, 2018707, 2100065, None, None, 68148, None, None, None, None, 2100065, '2,2021-05-02', datetime.date(2021, 5, 2), 68148, 347, None, None, 9315.62651648224, 2100065.0, None, 0.5091858895345425, 84000002.0, 'USA', 287072.56559746835, None, '2,2021-05-02', datetime.date(2021, 5, 2), None, 0, 77, None, None, 'Alaska, US', '2,2021-05-02,Unknown', datetime.date(2021, 5, 2), 'Alaska, US', 263330, 45132, '2,2021-05-02', 2, 6),
 (datetime.date(2021, 5, 9), 68880, 68880, 0, 79149, 2059510, 2141739, None, None, 68880, None, None, None, None, 2141739, '2,2021-05-09', datetime.date(2021, 5, 9), 68880, 349, None, None, 9415.68871361297, 2141739.0, None, 0.506678281068525, 84000002.0, 'USA', 292769.27598438924, None, '2,2021-05-09', datetime.date(2021, 5, 9), None, 0, 83, None, None, 'Alaska, US', '2,2021-05-09,Unknown', datetime.date(2021, 5, 9), 'Alaska, US', 288320, 44130, '2,2021-05-09', 2, 6)]

#### Create day_dim table

* Selecting distinct dates

In [153]:
%%sql
SELECT DISTINCT date
from merge
UNION
SELECT DISTINCT last_update
from merge
UNION
SELECT DISTINCT date1
from merge
UNION
SELECT DISTINCT date2
from merge
limit 10

 * postgresql://student@/week11
10 rows affected.


[(datetime.date(2020, 6, 4),),
 (datetime.date(2020, 7, 8),),
 (datetime.date(2021, 11, 4),),
 (datetime.date(2020, 12, 15),),
 (datetime.date(2021, 11, 13),),
 (datetime.date(2020, 3, 25),),
 (datetime.date(2020, 3, 26),),
 (datetime.date(2020, 12, 12),),
 (datetime.date(2021, 3, 9),),
 (None,)]

* Creating a new view as view3 that contains distinct dates

In [154]:
%%sql
CREATE OR REPLACE VIEW view3 AS (
SELECT DISTINCT date
from merge
UNION
SELECT DISTINCT last_update
from merge
UNION
SELECT DISTINCT date1
from merge
UNION
SELECT DISTINCT date2
from merge
ORDER BY date
)

 * postgresql://student@/week11
Done.


[]

* Check view

In [155]:
%%sql
SELECT * from view3
limit 10

 * postgresql://student@/week11
10 rows affected.


[(datetime.date(2020, 1, 13),),
 (datetime.date(2020, 1, 14),),
 (datetime.date(2020, 1, 15),),
 (datetime.date(2020, 1, 16),),
 (datetime.date(2020, 1, 17),),
 (datetime.date(2020, 1, 18),),
 (datetime.date(2020, 1, 19),),
 (datetime.date(2020, 1, 20),),
 (datetime.date(2020, 1, 21),),
 (datetime.date(2020, 1, 22),)]

* Creating a new dimension table day_dim

In [156]:
%%sql
--ALTER TABLE merge DROP CONSTRAINT fk_day;
DROP TABLE IF EXISTS day_dim;

CREATE TABLE day_dim (
    day_key SERIAL PRIMARY KEY,
    date date,
    year INTEGER,
    month_of_year_str VARCHAR(12),
    month_of_year INTEGER,
    day_of_month INTEGER,
    day_of_week_str CHAR(9),
    day_of_week INTEGER,
    is_weekend BOOLEAN,
    is_weekday BOOLEAN,
    quarter_of_year INTEGER
);

 * postgresql://student@/week11
Done.
Done.


[]

* Making elaborative day_dim table by inserting yearwise, querterwise, daywise information in different columns

In [157]:
%%sql
INSERT INTO day_dim (date, year, month_of_year_str, month_of_year, day_of_month, 
                  day_of_week_str, day_of_week, is_weekend, is_weekday, quarter_of_year)
SELECT date AS date, 
    CAST(TO_CHAR(date, 'YYYY') AS INTEGER) AS year,
    TO_CHAR(date, 'Month') AS month_of_year_str,
    CAST(TO_CHAR(date, 'MM') AS INTEGER) AS month_of_year,
    CAST(TO_CHAR(date, 'DD') AS INTEGER) AS day_of_month,
    TO_CHAR(date, 'Day') AS day_of_week_str,
    CAST(TO_CHAR(date, 'D') AS INTEGER) AS day_of_week,
    CASE WHEN CAST(TO_CHAR(date, 'D') AS INTEGER) IN (1, 7) 
        THEN TRUE
        ELSE FALSE
    END AS is_weekend,
    CASE WHEN CAST(TO_CHAR(date, 'D') AS INTEGER) NOT IN (1, 7) 
        THEN TRUE
        ELSE FALSE
    END AS is_weekday,
    CAST(TO_CHAR(date, 'Q') AS INTEGER) AS quarter_of_year
FROM view3

 * postgresql://student@/week11
699 rows affected.


[]

### Dimension table - day_dim final 

In [158]:
%%sql
SELECT * FROM day_dim
limit 10

 * postgresql://student@/week11
10 rows affected.


[(1, datetime.date(2020, 1, 13), 2020, 'January  ', 1, 13, 'Monday   ', 2, False, True, 1),
 (2, datetime.date(2020, 1, 14), 2020, 'January  ', 1, 14, 'Tuesday  ', 3, False, True, 1),
 (3, datetime.date(2020, 1, 15), 2020, 'January  ', 1, 15, 'Wednesday', 4, False, True, 1),
 (4, datetime.date(2020, 1, 16), 2020, 'January  ', 1, 16, 'Thursday ', 5, False, True, 1),
 (5, datetime.date(2020, 1, 17), 2020, 'January  ', 1, 17, 'Friday   ', 6, False, True, 1),
 (6, datetime.date(2020, 1, 18), 2020, 'January  ', 1, 18, 'Saturday ', 7, True, False, 1),
 (7, datetime.date(2020, 1, 19), 2020, 'January  ', 1, 19, 'Sunday   ', 1, True, False, 1),
 (8, datetime.date(2020, 1, 20), 2020, 'January  ', 1, 20, 'Monday   ', 2, False, True, 1),
 (9, datetime.date(2020, 1, 21), 2020, 'January  ', 1, 21, 'Tuesday  ', 3, False, True, 1),
 (10, datetime.date(2020, 1, 22), 2020, 'January  ', 1, 22, 'Wednesday', 4, False, True, 1)]

* Checking the weekday and weekend values

In [159]:
%%sql
SELECT DISTINCT day_of_week_str, day_of_week, is_weekend, is_weekday 
FROM day_dim
WHERE day_of_week is not null
ORDER BY day_of_week;

 * postgresql://student@/week11
7 rows affected.


[('Sunday   ', 1, True, False),
 ('Monday   ', 2, False, True),
 ('Tuesday  ', 3, False, True),
 ('Wednesday', 4, False, True),
 ('Thursday ', 5, False, True),
 ('Friday   ', 6, False, True),
 ('Saturday ', 7, True, False)]

* Adding foreign key constraint in the merge table as per the day_dim table

In [160]:
%%sql
ALTER TABLE merge
ADD COLUMN day_key INTEGER,
ADD CONSTRAINT fk_day
    FOREIGN KEY (day_key)
    REFERENCES day_dim (day_key);

 * postgresql://student@/week11
Done.


[]

* Update the day_key values in the merge table

In [161]:
%%sql
UPDATE merge
SET day_key = day_dim.day_key
FROM day_dim
WHERE merge.date = day_dim.date or merge.date1 = day_dim.date or merge.date2 = day_dim.date or merge.last_update = day_dim.date

 * postgresql://student@/week11
126652 rows affected.


[]

* Check table

In [162]:
%%sql
SELECT * from merge
limit 5

 * postgresql://student@/week11
5 rows affected.


[(datetime.date(2021, 4, 11), 64782, 64782, 0, 74611, 1888767, 1966048, None, None, 64782, None, None, None, None, 1966048, '2,2021-04-11', datetime.date(2021, 4, 11), 64782, 313, None, None, 8855.504446069619, 1966048.0, None, 0.4831589021641814, 84000002.0, 'USA', 268752.8450061172, None, '2,2021-04-11', datetime.date(2021, 4, 11), None, 0, 306, None, None, 'Alaska, US', '2,2021-04-11,Unknown', datetime.date(2021, 4, 11), 'Alaska, US', 203259, 72046, '2,2021-04-11', 2, 6, 455),
 (datetime.date(2021, 4, 18), 65921, 65921, 0, 75886, 1930980, 2009651, None, None, 65921, None, None, None, None, 2009651, '2,2021-04-18', datetime.date(2021, 4, 18), 65921, 334, None, None, 9011.202318380962, 2009651.0, None, 0.5066670711912744, 84000002.0, 'USA', 274713.24388793577, None, '2,2021-04-18', datetime.date(2021, 4, 18), None, 0, 72, None, None, 'Alaska, US', '2,2021-04-18,Unknown', datetime.date(2021, 4, 18), 'Alaska, US', 234735, 55950, '2,2021-04-18', 2, 6, 462),
 (datetime.date(2021, 4, 25), 67059, 67059, 0, 77171, 1972943, 2053055, None, None, 67059, None, None, None, None, 2053055, '2,2021-04-25', datetime.date(2021, 4, 25), 67059, 334, None, None, 9166.763493701686, 2053055.0, None, 0.4980688647310577, 84000002.0, 'USA', 280646.4400686219, None, '2,2021-04-25', datetime.date(2021, 4, 25), None, 0, 77, None, None, 'Alaska, US', '2,2021-04-25,Unknown', datetime.date(2021, 4, 25), 'Alaska, US', 251843, 51923, '2,2021-04-25', 2, 6, 469),
 (datetime.date(2021, 5, 2), 68148, 68148, 0, 78329, 2018707, 2100065, None, None, 68148, None, None, None, None, 2100065, '2,2021-05-02', datetime.date(2021, 5, 2), 68148, 347, None, None, 9315.62651648224, 2100065.0, None, 0.5091858895345425, 84000002.0, 'USA', 287072.56559746835, None, '2,2021-05-02', datetime.date(2021, 5, 2), None, 0, 77, None, None, 'Alaska, US', '2,2021-05-02,Unknown', datetime.date(2021, 5, 2), 'Alaska, US', 263330, 45132, '2,2021-05-02', 2, 6, 476),
 (datetime.date(2021, 5, 9), 68880, 68880, 0, 79149, 2059510, 2141739, None, None, 68880, None, None, None, None, 2141739, '2,2021-05-09', datetime.date(2021, 5, 9), 68880, 349, None, None, 9415.68871361297, 2141739.0, None, 0.506678281068525, 84000002.0, 'USA', 292769.27598438924, None, '2,2021-05-09', datetime.date(2021, 5, 9), None, 0, 83, None, None, 'Alaska, US', '2,2021-05-09,Unknown', datetime.date(2021, 5, 9), 'Alaska, US', 288320, 44130, '2,2021-05-09', 2, 6, 483)]

* Drop columns from fact table "merge" as we have inserted these columns in the day_dim table

In [163]:
%%sql
ALTER TABLE merge
DROP COLUMN date CASCADE,
DROP COLUMN date1,
DROP COLUMN date2,
DROP COLUMN last_update;

 * postgresql://student@/week11
Done.


[]

* Check table

In [164]:
%%sql
SELECT * from merge
limit 5

 * postgresql://student@/week11
5 rows affected.


[(64782, 64782, 0, 74611, 1888767, 1966048, None, None, 64782, None, None, None, None, 1966048, '2,2021-04-11', 64782, 313, None, None, 8855.504446069619, 1966048.0, None, 0.4831589021641814, 84000002.0, 'USA', 268752.8450061172, None, '2,2021-04-11', None, 0, 306, None, None, 'Alaska, US', '2,2021-04-11,Unknown', 'Alaska, US', 203259, 72046, '2,2021-04-11', 2, 6, 455),
 (65921, 65921, 0, 75886, 1930980, 2009651, None, None, 65921, None, None, None, None, 2009651, '2,2021-04-18', 65921, 334, None, None, 9011.202318380962, 2009651.0, None, 0.5066670711912744, 84000002.0, 'USA', 274713.24388793577, None, '2,2021-04-18', None, 0, 72, None, None, 'Alaska, US', '2,2021-04-18,Unknown', 'Alaska, US', 234735, 55950, '2,2021-04-18', 2, 6, 462),
 (67059, 67059, 0, 77171, 1972943, 2053055, None, None, 67059, None, None, None, None, 2053055, '2,2021-04-25', 67059, 334, None, None, 9166.763493701686, 2053055.0, None, 0.4980688647310577, 84000002.0, 'USA', 280646.4400686219, None, '2,2021-04-25', None, 0, 77, None, None, 'Alaska, US', '2,2021-04-25,Unknown', 'Alaska, US', 251843, 51923, '2,2021-04-25', 2, 6, 469),
 (68148, 68148, 0, 78329, 2018707, 2100065, None, None, 68148, None, None, None, None, 2100065, '2,2021-05-02', 68148, 347, None, None, 9315.62651648224, 2100065.0, None, 0.5091858895345425, 84000002.0, 'USA', 287072.56559746835, None, '2,2021-05-02', None, 0, 77, None, None, 'Alaska, US', '2,2021-05-02,Unknown', 'Alaska, US', 263330, 45132, '2,2021-05-02', 2, 6, 476),
 (68880, 68880, 0, 79149, 2059510, 2141739, None, None, 68880, None, None, None, None, 2141739, '2,2021-05-09', 68880, 349, None, None, 9415.68871361297, 2141739.0, None, 0.506678281068525, 84000002.0, 'USA', 292769.27598438924, None, '2,2021-05-09', None, 0, 83, None, None, 'Alaska, US', '2,2021-05-09,Unknown', 'Alaska, US', 288320, 44130, '2,2021-05-09', 2, 6, 483)]

### Remove extra columns

* Drop all unnecesary dimensions from the fact table - merge

In [165]:
%%sql
ALTER TABLE merge
DROP COLUMN primary_key,
DROP COLUMN uid,
DROP COLUMN iso3,
DROP COLUMN primary_key1,
DROP COLUMN combined_key,
DROP COLUMN primary_key2,
DROP COLUMN combined_key1,
DROP COLUMN primary_key3

 * postgresql://student@/week11
Done.


[]

#### Merge final table (fact)

In [166]:
%%sql
SELECT * from merge
where cases_confirmed is not null
limit 5

 * postgresql://student@/week11
5 rows affected.


[(64782, 64782, 0, 74611, 1888767, 1966048, None, None, 64782, None, None, None, None, 1966048, 64782, 313, None, None, 8855.504446069619, 1966048.0, None, 0.4831589021641814, 268752.8450061172, None, None, 0, 306, None, None, 203259, 72046, 2, 6, 455),
 (65921, 65921, 0, 75886, 1930980, 2009651, None, None, 65921, None, None, None, None, 2009651, 65921, 334, None, None, 9011.202318380962, 2009651.0, None, 0.5066670711912744, 274713.24388793577, None, None, 0, 72, None, None, 234735, 55950, 2, 6, 462),
 (67059, 67059, 0, 77171, 1972943, 2053055, None, None, 67059, None, None, None, None, 2053055, 67059, 334, None, None, 9166.763493701686, 2053055.0, None, 0.4980688647310577, 280646.4400686219, None, None, 0, 77, None, None, 251843, 51923, 2, 6, 469),
 (68148, 68148, 0, 78329, 2018707, 2100065, None, None, 68148, None, None, None, None, 2100065, 68148, 347, None, None, 9315.62651648224, 2100065.0, None, 0.5091858895345425, 287072.56559746835, None, None, 0, 77, None, None, 263330, 45132, 2, 6, 476),
 (68880, 68880, 0, 79149, 2059510, 2141739, None, None, 68880, None, None, None, None, 2141739, 68880, 349, None, None, 9415.68871361297, 2141739.0, None, 0.506678281068525, 292769.27598438924, None, None, 0, 83, None, None, 288320, 44130, 2, 6, 483)]

# Ask 6: Analytical Questions
Write queries to answer your analytical questions
-Produce charts and make sure to include your code or a copy of chart (if you use outside Jupyter notebook tools). You are free to use any tool for visualization (e.g. tableau, ggplot,
matplotlib,..)

##### Expectation: set of queries, results and charts. Those should be compatible with your presentation.

#### Q1. Does the rate of testing in a state impact the number of deaths? - Number of tests (Tests Viral Total) per capita vs number of deaths (Deaths) per capita in a given state

##### For California state

In [167]:
%%sql
select distinct state_dim.state_us, merge.tests_viral_total, merge.deaths, 
                cast(deaths as float)/cast(tests_viral_total as float) AS ratio, day_dim.date
from merge, day_dim, state_dim
where merge.state_key = state_dim.state_key 
and merge.day_key = day_dim.day_key
and day_dim.date Between '2021-04-09' and '2021-12-01' 
and state_dim.state_us = 'California'
order by date
limit 10

 * postgresql://student@/week11
10 rows affected.


[('California', 55827642, 58971, 0.0010563046886343508, datetime.date(2021, 4, 9)),
 ('California', 56078860, 59147, 0.0010547111692356087, datetime.date(2021, 4, 10)),
 ('California', 56363675, 59250, 0.0010512089568325699, datetime.date(2021, 4, 11)),
 ('California', 56363675, 59298, 0.0010520605691520292, datetime.date(2021, 4, 12)),
 ('California', 56722428, 59315, 0.0010457062945189864, datetime.date(2021, 4, 13)),
 ('California', 56837538, 59410, 0.0010452599125599, datetime.date(2021, 4, 14)),
 ('California', 56997332, 59539, 0.0010445927539204818, datetime.date(2021, 4, 15)),
 ('California', 57228812, 59627, 0.0010419052556953304, datetime.date(2021, 4, 16)),
 ('California', 57481126, 59731, 0.0010391410912862075, datetime.date(2021, 4, 17)),
 ('California', 57733460, 59813, 0.0010360196669314467, datetime.date(2021, 4, 18))]

In [168]:
from IPython.display import Image
Image(url="https://github.com/pkbhatta5/GWU-DNSC-6305/blob/3cad1ac1ac40893a5cd10ea6addd504f7a68a71f/Q1.1.png?raw=true")

##### Observations:
* The plot of death and testing ratio shows a slow decrease as the number of actual tests increase and deaths decrease in CA.

##### For Georgia state

In [169]:
%%sql
select distinct state_dim.state_us, merge.tests_viral_total, merge.deaths, 
                cast(deaths as float)/cast(tests_viral_total as float) AS ratio, day_dim.date
from merge, day_dim, state_dim
where merge.state_key = state_dim.state_key 
and merge.day_key = day_dim.day_key
and day_dim.date Between '2021-04-09' and '2021-12-01' 
and state_dim.state_us = 'Georgia'
order by date
limit 10

 * postgresql://student@/week11
10 rows affected.


[('Georgia', 7955525, 19374, 0.0024352886830221764, datetime.date(2021, 4, 9)),
 ('Georgia', 7975847, 19424, 0.0024353526340211893, datetime.date(2021, 4, 10)),
 ('Georgia', 7990341, 19488, 0.0024389447208823752, datetime.date(2021, 4, 11)),
 ('Georgia', 8001348, 19488, 0.002435589603151869, datetime.date(2021, 4, 12)),
 ('Georgia', 8015034, 19523, 0.0024357975274964523, datetime.date(2021, 4, 13)),
 ('Georgia', 8033081, 19548, 0.0024334374320388406, datetime.date(2021, 4, 14)),
 ('Georgia', 8052865, 19600, 0.0024339163763455614, datetime.date(2021, 4, 15)),
 ('Georgia', 8074059, 19662, 0.002435206381325675, datetime.date(2021, 4, 16)),
 ('Georgia', 8095179, 19718, 0.0024357707223027435, datetime.date(2021, 4, 17)),
 ('Georgia', 8108632, 19757, 0.002436539233744977, datetime.date(2021, 4, 18))]

In [170]:
from IPython.display import Image
Image(url="https://github.com/pkbhatta5/GWU-DNSC-6305/blob/3cad1ac1ac40893a5cd10ea6addd504f7a68a71f/Q1.2.png?raw=true")

##### Observations:
* This chart shows the ratio between deaths and tests in Georgia. 
* There is a decrease in deaths, likely as vaccine rates increase, but after September 9th the rate of deaths to testing increases. 
* This could be due to a higher actual number of deaths, or a decreased rate of testing as more people are vaccinated and people are not as concerned. 

#### Q2. In states where testing is higher, is vaccination also high? - Vaccine rollout (people fully vaccinated) vs rate of testing (Tests Viral Total) 

##### For California state

In [171]:
%%sql
select distinct state_dim.state_us, merge.tests_viral_total, merge.people_fully_vaccinated, 
                cast(tests_viral_total as float)/cast(people_fully_vaccinated as float) AS ratio, day_dim.date
from merge, day_dim, state_dim
where merge.state_key = state_dim.state_key 
and merge.day_key = day_dim.day_key
and day_dim.date Between '2021-04-09' and '2021-12-08' 
and state_dim.state_us = 'California'
order by date
limit 10

 * postgresql://student@/week11
10 rows affected.


[('California', 55827642, 7599559, 7.346168639522372, datetime.date(2021, 4, 9)),
 ('California', 56078860, 8376151, 6.695063162065727, datetime.date(2021, 4, 10)),
 ('California', 56363675, 8619032, 6.539443756561061, datetime.date(2021, 4, 11)),
 ('California', 56363675, 8767321, 6.428836699374871, datetime.date(2021, 4, 12)),
 ('California', 56722428, 8871326, 6.393906390093206, datetime.date(2021, 4, 13)),
 ('California', 56837538, 8871326, 6.406881902434878, datetime.date(2021, 4, 14)),
 ('California', 56997332, 9531578, 5.979842162546433, datetime.date(2021, 4, 15)),
 ('California', 57228812, 9774849, 5.854700364169308, datetime.date(2021, 4, 16)),
 ('California', 57481126, 9998574, 5.748932397759921, datetime.date(2021, 4, 17)),
 ('California', 57733460, 10149469, 5.688323201933027, datetime.date(2021, 4, 18))]

In [172]:
from IPython.display import Image
Image(url="https://github.com/pkbhatta5/GWU-DNSC-6305/blob/3cad1ac1ac40893a5cd10ea6addd504f7a68a71f/Q2.1.png?raw=true")

##### Observations:
* This chart shows the rate of total viral tests and fully vaccinated people in California. 
* It is clear that there is a sharp downturn in the rate of viral tests as the vaccination effort develops and the number of vaccinated individuals increase. 
* However, there is a slow increase in viral tests after the sharp drop as the immunity of vaccines provided wears off over time.

##### For Georgia state

In [173]:
%%sql
select distinct state_dim.state_us, merge.tests_viral_total, merge.people_fully_vaccinated, 
                cast(tests_viral_total as float)/cast(people_fully_vaccinated as float) AS ratio, day_dim.date
from merge, day_dim, state_dim
where merge.state_key = state_dim.state_key 
and merge.day_key = day_dim.day_key
and day_dim.date Between '2021-04-09' and '2021-12-08' 
and state_dim.state_us = 'Georgia'
order by date
limit 10

 * postgresql://student@/week11
10 rows affected.


[('Georgia', 7955525, 1536865, 5.176463124607562, datetime.date(2021, 4, 9)),
 ('Georgia', 7975847, 1648756, 4.83749384384348, datetime.date(2021, 4, 10)),
 ('Georgia', 7990341, 1699220, 4.702358140794011, datetime.date(2021, 4, 11)),
 ('Georgia', 8001348, 1729962, 4.6251582404700216, datetime.date(2021, 4, 12)),
 ('Georgia', 8015034, 1744617, 4.594151037161738, datetime.date(2021, 4, 13)),
 ('Georgia', 8033081, 1788215, 4.4922344348973695, datetime.date(2021, 4, 14)),
 ('Georgia', 8052865, 1906645, 4.22357858961684, datetime.date(2021, 4, 15)),
 ('Georgia', 8074059, 1977356, 4.083260171663575, datetime.date(2021, 4, 16)),
 ('Georgia', 8095179, 2029324, 3.989101296786516, datetime.date(2021, 4, 17)),
 ('Georgia', 8108632, 2077348, 3.903357550107156, datetime.date(2021, 4, 18))]

In [174]:
from IPython.display import Image
Image(url="https://github.com/pkbhatta5/GWU-DNSC-6305/blob/3cad1ac1ac40893a5cd10ea6addd504f7a68a71f/Q2.2.png?raw=true")

##### Observations:
* This chart shows the rate of total viral tests and fully vaccinated people in Georgia. 
* There is a sharp downturn in the rate of viral tests as the vaccination effort develops and the number of vaccinated individuals increase. 
* However, there is a slow increase in viral tests after the sharp drop as the immunity of vaccines provided wears off over time.

#### Q3. Did vaccinations have any effect on confirmed cases over a period of time? – Confirmed cases vs people vaccinated 

##### For California state

In [175]:
%%sql
SELECT DISTINCT state_dim.state_us, merge.confirmed, merge.people_fully_vaccinated, day_dim.date
from merge, state_dim, day_dim
where merge.state_key = state_dim.state_key 
and merge.day_key = day_dim.day_key
and day_dim.date Between '2021-02-08' and '2021-12-01'
and state_dim.state_us = 'California'
order by date
limit 10;

 * postgresql://student@/week11
10 rows affected.


[('California', 3482110, 808832, datetime.date(2021, 2, 8)),
 ('California', 3491560, 847993, datetime.date(2021, 2, 9)),
 ('California', 3501317, 875340, datetime.date(2021, 2, 10)),
 ('California', 3510460, 928615, datetime.date(2021, 2, 11)),
 ('California', 3521446, 990128, datetime.date(2021, 2, 12)),
 ('California', 3531194, 1081040, datetime.date(2021, 2, 13)),
 ('California', 3541508, 1178577, datetime.date(2021, 2, 14)),
 ('California', 3548296, 1287390, datetime.date(2021, 2, 15)),
 ('California', 3554093, 1287390, datetime.date(2021, 2, 16)),
 ('California', 3559267, 1456222, datetime.date(2021, 2, 17))]

In [176]:
from IPython.display import Image
Image(url="https://github.com/pkbhatta5/GWU-DNSC-6305/blob/3cad1ac1ac40893a5cd10ea6addd504f7a68a71f/Q3.1.png?raw=true")

##### Observations:
* In California the change after reopening is not very severe, but still noticeable. 

##### For Georgia state

In [177]:
%%sql
SELECT DISTINCT state_dim.state_us, merge.confirmed, merge.people_fully_vaccinated, day_dim.date
from merge, state_dim, day_dim
where merge.state_key = state_dim.state_key 
and merge.day_key = day_dim.day_key
and day_dim.date Between '2021-02-09' and '2021-12-01'
and state_dim.state_us = 'Georgia'
order by date
limit 10;

 * postgresql://student@/week11
10 rows affected.


[('Georgia', 943695, 219840, datetime.date(2021, 2, 9)),
 ('Georgia', 947416, 227997, datetime.date(2021, 2, 10)),
 ('Georgia', 950906, 251946, datetime.date(2021, 2, 11)),
 ('Georgia', 955085, 279546, datetime.date(2021, 2, 12)),
 ('Georgia', 958985, 279546, datetime.date(2021, 2, 13)),
 ('Georgia', 962808, 313961, datetime.date(2021, 2, 14)),
 ('Georgia', 964737, 380394, datetime.date(2021, 2, 15)),
 ('Georgia', 966807, 403128, datetime.date(2021, 2, 16)),
 ('Georgia', 969702, 433618, datetime.date(2021, 2, 17)),
 ('Georgia', 973247, 464133, datetime.date(2021, 2, 18))]

In [178]:
from IPython.display import Image
Image(url="https://github.com/pkbhatta5/GWU-DNSC-6305/blob/3cad1ac1ac40893a5cd10ea6addd504f7a68a71f/Q3.2.png?raw=true")

##### Observations:
* In Georgia the sharp rise in cases is more severe than in California, showing that the combination of reopening and the Delta variant had a greater impact in GA than CA.

##### Combined Observations:
* These two charts above show that the number of vaccinated individuals increases at a faster rate compared to the confirmed cases. 
* However, after Delta starts in March 2021, we see the repercussions in August 2021 after restrictions are lifted during June 2021 and July 2021. 
* This shows that vaccinations are important, but restrictions and social distancing has a significant impact on the rate of confirmed cases especially as variants continue to be a pressing issue. 

#### Q4. For the number of doses shipped out, how many vaccinations are actually going into arms? - doses shipped vs doses administered

##### For California state

In [179]:
%%sql
SELECT distinct state_dim.state_us, merge.doses_shipped, merge.doses_admin, 
                cast(doses_shipped as float)/cast(doses_admin as float) as ratio, day_dim.date
FROM state_dim, vaccine_dim, merge, day_dim
WHERE merge.state_key = state_dim.state_key 
and merge.vaccine_key = vaccine_dim.vaccine_key 
and merge.day_key = day_dim.day_key
and day_dim.date between '2021-01-06' and '2021-12-01' 
and doses_admin != 0 
and doses_shipped is not null 
and state_dim.state_us = 'California'
ORDER BY date
Limit 10

 * postgresql://student@/week11
10 rows affected.


[('California', 2007600, 488515, 4.109597453507057, datetime.date(2021, 1, 6)),
 ('California', 2007600, 586379, 3.4237242466050115, datetime.date(2021, 1, 7)),
 ('California', 2060800, 652128, 3.1601158054860394, datetime.date(2021, 1, 8)),
 ('California', 2060800, 734405, 2.806081113282181, datetime.date(2021, 1, 9)),
 ('California', 2180725, 734405, 2.969376570148624, datetime.date(2021, 1, 10)),
 ('California', 2919925, 783476, 3.7268850609335833, datetime.date(2021, 1, 11)),
 ('California', 2466125, 816673, 3.0197214797109737, datetime.date(2021, 1, 12)),
 ('California', 2862350, 889042, 3.2195891757644746, datetime.date(2021, 1, 13)),
 ('California', 2948350, 971829, 3.0338156198261217, datetime.date(2021, 1, 14)),
 ('California', 2948350, 971829, 3.0338156198261217, datetime.date(2021, 1, 15))]

In [180]:
from IPython.display import Image
Image(url="https://github.com/pkbhatta5/GWU-DNSC-6305/blob/3cad1ac1ac40893a5cd10ea6addd504f7a68a71f/Q4.1.png?raw=true")

##### For Georgia state

In [181]:
%%sql
SELECT distinct state_dim.state_us, sum(merge.doses_shipped) as doses_shipped, sum(merge.doses_admin) as doses_admin, 
                cast(sum(doses_shipped) as float)/cast(sum(doses_admin) as float) as ratio, day_dim.date
FROM state_dim, vaccine_dim, merge, day_dim
WHERE merge.state_key = state_dim.state_key 
and merge.vaccine_key = vaccine_dim.vaccine_key 
and merge.day_key = day_dim.day_key
and day_dim.date between '2020-12-20' and '2021-12-01' 
and doses_admin != 0 
and doses_shipped is not null 
and state_dim.state_us = 'Georgia'
GROUP BY state_us, day_dim.date
ORDER BY date
Limit 10

 * postgresql://student@/week11
10 rows affected.


[('Georgia', 148200, 2516, 58.90302066772655, datetime.date(2020, 12, 20)),
 ('Georgia', 282550, 35740, 7.90570789031897, datetime.date(2020, 12, 21)),
 ('Georgia', 410050, 52020, 7.8825451749327184, datetime.date(2020, 12, 22)),
 ('Georgia', 410050, 52020, 7.8825451749327184, datetime.date(2020, 12, 23)),
 ('Georgia', 410050, 52020, 7.8825451749327184, datetime.date(2020, 12, 24)),
 ('Georgia', 410050, 52020, 7.8825451749327184, datetime.date(2020, 12, 25)),
 ('Georgia', 410050, 52020, 7.8825451749327184, datetime.date(2020, 12, 26)),
 ('Georgia', 410050, 52020, 7.8825451749327184, datetime.date(2020, 12, 27)),
 ('Georgia', 548400, 104484, 5.248650511083037, datetime.date(2020, 12, 28)),
 ('Georgia', 552800, 123740, 4.467431711653467, datetime.date(2020, 12, 29))]

In [182]:
from IPython.display import Image
Image(url="https://github.com/pkbhatta5/GWU-DNSC-6305/blob/3cad1ac1ac40893a5cd10ea6addd504f7a68a71f/Q4.2.png?raw=true")

##### Combined Observations:
* The doses that were administered per doses shipped, to both CA and Gerogia, are uneven in the start of the vaccination effort.
* However, as the supply chain, distribution, and other kinks are smoothed out, the rate stabilizes. 
* Also, there is a clear disturbance in California on Nov 3 as doses shipped is very low per doses administered, which indicates a disturbance in the supply chain.

#### 5.Did the confirmed cases have a big difference before and after California reopened on June 15th, 2021 and DC reopened on June 11th, 2021? - confirmed cases

##### Checking for California before reopening (2 months prior to june 15th) 

In [183]:
%%sql
SELECT DISTINCT state_dim.state_us, merge.cases_confirmed, day_dim.date
from merge, state_dim, day_dim
where merge.state_key = state_dim.state_key 
and merge.day_key = day_dim.day_key
and day_dim.date Between '2021-04-09' and '2021-06-15'
and state_dim.state_us = 'California'
order by date
limit 10;

 * postgresql://student@/week11
10 rows affected.


[('California', 3590758, datetime.date(2021, 4, 9)),
 ('California', 3595224, datetime.date(2021, 4, 10)),
 ('California', 3600178, datetime.date(2021, 4, 11)),
 ('California', 3602827, datetime.date(2021, 4, 12)),
 ('California', 3604395, datetime.date(2021, 4, 13)),
 ('California', 3606882, datetime.date(2021, 4, 14)),
 ('California', 3608898, datetime.date(2021, 4, 15)),
 ('California', 3611349, datetime.date(2021, 4, 16)),
 ('California', 3614112, datetime.date(2021, 4, 17)),
 ('California', 3616779, datetime.date(2021, 4, 18))]

In [184]:
from IPython.display import Image
Image(url="https://github.com/pkbhatta5/GWU-DNSC-6305/blob/3cad1ac1ac40893a5cd10ea6addd504f7a68a71f/Q5.1.png?raw=true")

##### Checking for California after reopening (2 months after june 15th) 

In [185]:
%%sql
SELECT DISTINCT state_dim.state_us, merge.cases_confirmed, day_dim.date
from merge, state_dim, day_dim
where merge.state_key = state_dim.state_key 
and merge.day_key = day_dim.day_key
and day_dim.date Between '2021-06-15' and '2021-08-21'
and state_dim.state_us = 'California'
order by date
limit 10;

 * postgresql://student@/week11
10 rows affected.


[('California', 3697927, datetime.date(2021, 6, 15)),
 ('California', 3698626, datetime.date(2021, 6, 16)),
 ('California', 3699455, datetime.date(2021, 6, 17)),
 ('California', 3700750, datetime.date(2021, 6, 18)),
 ('California', 3701926, datetime.date(2021, 6, 19)),
 ('California', 3702882, datetime.date(2021, 6, 20)),
 ('California', 3704005, datetime.date(2021, 6, 21)),
 ('California', 3704640, datetime.date(2021, 6, 22)),
 ('California', 3705427, datetime.date(2021, 6, 23)),
 ('California', 3706846, datetime.date(2021, 6, 24))]

In [186]:
from IPython.display import Image
Image(url="https://github.com/pkbhatta5/GWU-DNSC-6305/blob/3cad1ac1ac40893a5cd10ea6addd504f7a68a71f/Q5.2.png?raw=true")

##### Observation:
* Confirmed cases in CA rise after reopening on June 15th which indicates the effectiveness and importance of social distancing measures. 

##### Checking for DC before reopening (2 months prior to june 11th) 

In [187]:
%%sql
SELECT DISTINCT state_dim.state_us, merge.cases_confirmed, day_dim.date
from merge, state_dim, day_dim
where merge.state_key = state_dim.state_key 
and merge.day_key = day_dim.day_key
and day_dim.date Between '2021-04-09' and '2021-06-11'
and state_dim.state_us = 'District of Columbia'
order by date
limit 10;

 * postgresql://student@/week11
10 rows affected.


[('District of Columbia', 45634, datetime.date(2021, 4, 9)),
 ('District of Columbia', 45762, datetime.date(2021, 4, 10)),
 ('District of Columbia', 45830, datetime.date(2021, 4, 11)),
 ('District of Columbia', 45903, datetime.date(2021, 4, 12)),
 ('District of Columbia', 46016, datetime.date(2021, 4, 13)),
 ('District of Columbia', 46209, datetime.date(2021, 4, 14)),
 ('District of Columbia', 46315, datetime.date(2021, 4, 15)),
 ('District of Columbia', 46449, datetime.date(2021, 4, 16)),
 ('District of Columbia', 46579, datetime.date(2021, 4, 17)),
 ('District of Columbia', 46662, datetime.date(2021, 4, 18))]

In [188]:
from IPython.display import Image
Image(url="https://github.com/pkbhatta5/GWU-DNSC-6305/blob/3cad1ac1ac40893a5cd10ea6addd504f7a68a71f/Q5.3.png?raw=true")

##### Checking for DC after reopening (2 months after june 11th) 

In [189]:
%%sql
SELECT DISTINCT state_dim.state_us, merge.cases_confirmed, day_dim.date
from merge, state_dim, day_dim
where merge.state_key = state_dim.state_key 
and merge.day_key = day_dim.day_key
and day_dim.date Between '2021-06-11' and '2021-08-13'
and state_dim.state_us = 'District of Columbia'
order by date
limit 10;

 * postgresql://student@/week11
10 rows affected.


[('District of Columbia', 49158, datetime.date(2021, 6, 11)),
 ('District of Columbia', 49158, datetime.date(2021, 6, 12)),
 ('District of Columbia', 49158, datetime.date(2021, 6, 13)),
 ('District of Columbia', 49158, datetime.date(2021, 6, 14)),
 ('District of Columbia', 49213, datetime.date(2021, 6, 15)),
 ('District of Columbia', 49223, datetime.date(2021, 6, 16)),
 ('District of Columbia', 49232, datetime.date(2021, 6, 17)),
 ('District of Columbia', 49243, datetime.date(2021, 6, 18)),
 ('District of Columbia', 49243, datetime.date(2021, 6, 19)),
 ('District of Columbia', 49243, datetime.date(2021, 6, 20))]

In [190]:
from IPython.display import Image
Image(url="https://github.com/pkbhatta5/GWU-DNSC-6305/blob/3cad1ac1ac40893a5cd10ea6addd504f7a68a71f/Q5.4.png?raw=true")

##### Observation:
* Confirmed cases in DC rise after reopening on June 11th which indicates the effectiveness and importance of social distancing measures. 